package dev.wareworks.gametest;

import java.util.Optional;

import dev.wareworks.Wareworks;
import dev.wareworks.config.WareworksConfig;
import dev.wareworks.content.item.ItemHandlerSnapshots;
import dev.wareworks.content.item.ItemKey;
import dev.wareworks.core.inventory.InventorySnapshot;
import dev.wareworks.registry.WareworksCreativeTabs;
import net.minecraft.core.BlockPos;
import net.minecraft.core.Direction;
import net.minecraft.core.HolderLookup;
import net.minecraft.core.component.DataComponents;
import net.minecraft.core.registries.BuiltInRegistries;
import net.minecraft.gametest.framework.GameTest;
import net.minecraft.gametest.framework.GameTestHelper;
import net.minecraft.nbt.CompoundTag;
import net.minecraft.nbt.StringTag;
import net.minecraft.nbt.Tag;
import net.minecraft.network.chat.Component;
import net.minecraft.world.item.ItemStack;
import net.minecraft.world.item.Items;
import net.minecraft.world.level.block.Blocks;
import net.neoforged.neoforge.capabilities.Capabilities;
import net.neoforged.neoforge.gametest.GameTestHolder;
import net.neoforged.neoforge.gametest.PrefixGameTestTemplate;
import net.neoforged.neoforge.items.IItemHandler;
import net.neoforged.neoforge.items.ItemHandlerHelper;

/**
 * Foundation GameTests: prove that the GameTest pipeline, the structure templates and the foundation classes work in a
 * real server.
 * <p>
 * Templates live in {@code data/wareworks/structure/<name>.nbt} and are generated by {@code scripts/gen_structures.py}.
 * They contain only a floor: template layer 0 is test-relative {@code y = 1} ({@link #FLOOR_Y}); test-relative
 * {@code y = 0} is the structure block layer and must never be built on.
 * <p>
 * Test names are the lowercased method names ({@code @PrefixGameTestTemplate(false)} drops the class prefix from both
 * template path and test name). Run one in a dev client or server with {@code /test run <name>}.
 */
@GameTestHolder(Wareworks.ID)
@PrefixGameTestTemplate(false)
public final class WareworksGameTests {
    /** 7 x 5 x 7 floor plate for small single-block tests. */
    public static final String EMPTY_7X5X7 = "empty_7x5x7";
    /**
     * 16 x 10 x 7 floor plate for aisle tests: an aisle along +X at z = 3 (controller x = 0, dock x = 1, up to 14 rails
     * x = 2..15), racks and inventories on both sides at z = 1..2 and z = 4..5, mast levels up to 6 above the dock.
     */
    public static final String AISLE_16X10X7 = "aisle_16x10x7";
    /**
     * 48 x 5 x 3 floor strip for long rail lines: a dock at x = 0, z = 1 with up to 47 rails x = 1..47 (rail cap tests).
     */
    public static final String RAIL_LINE_48X5X3 = "rail_line_48x5x3";
    /**
     * 16 x 10 x 13 floor plate with room for two parallel aisles along +X: the {@link #AISLE_16X10X7} layout at z = 3 and
     * again at z = 9 (side-by-side comparisons, e.g. throughput at different speeds).
     */
    public static final String AISLE_PAIR_16X10X13 = "aisle_pair_16x10x13";

    /** Test-relative y of the template floor. */
    public static final int FLOOR_Y = 1;
    /** First free layer above the floor. */
    public static final int BASE_Y = 2;

    /**
     * Bound of a warehouse interface's update tag in NBT size accounting ({@code Tag#sizeInBytes}) without reservations:
     * the goggle summary (at most 3 item ids and counts) and the aisle assignment. Almost every interface of a rack wall is
     * in this state; syncing item components would exceed it by orders of magnitude.
     */
    public static final int MAX_INTERFACE_SYNC_BYTES = 2048;
    /**
     * Bound of a warehouse interface's update tag with the largest reservation summary (2 incoming and 2 outgoing item
     * types with long ids). Only the locations of running jobs have reservations. The accounting counts 36 + 2 bytes per
     * character for every string, far more than is sent ({@code docs/warehouse-system.md} §3.1.1).
     */
    public static final int MAX_RESERVED_INTERFACE_SYNC_BYTES = 4096;

    private static final int CHEST_SLOTS = 27;
    private static final int INSERTED_IRON = 100;
    private static final int LARGE_COUNT = 150;
    private static final int PROBE_AMOUNT = 100_000;

    private WareworksGameTests() {
    }

    /** Infrastructure smoke test: a chest placed via the helper is readable through the item capability. */
    @GameTest(template = EMPTY_7X5X7)
    public static void chestSnapshot(GameTestHelper helper) {
        BlockPos chestPos = new BlockPos(3, BASE_Y, 3);
        helper.setBlock(chestPos, Blocks.CHEST);
        helper.assertBlockPresent(Blocks.CHEST, chestPos);

        IItemHandler handler = helper.getLevel()
                .getCapability(Capabilities.ItemHandler.BLOCK, helper.absolutePos(chestPos), null);
        if (handler == null)
            helper.fail("chest exposes no item handler", chestPos);

        ItemStack named = new ItemStack(Items.IRON_INGOT);
        named.set(DataComponents.CUSTOM_NAME, Component.literal("Wareworks test ingot"));
        insertAll(helper, handler, new ItemStack(Items.IRON_INGOT, INSERTED_IRON));
        insertAll(helper, handler, named.copy());

        InventorySnapshot<ItemKey> snapshot = ItemHandlerSnapshots.capture(handler);
        ItemKey iron = ItemKey.of(Items.IRON_INGOT);
        helper.assertValueEqual(snapshot.totalSlots(), CHEST_SLOTS, "total slots");
        helper.assertValueEqual(snapshot.usedSlots(), 3, "used slots (64 + 36 plain, 1 named)");
        helper.assertValueEqual(snapshot.count(iron), (long) INSERTED_IRON, "plain iron count");
        helper.assertValueEqual(snapshot.count(ItemKey.of(named)), 1L, "named iron count");
        helper.assertValueEqual(snapshot.keys().size(), 2, "distinct keys (components matter)");
        helper.assertValueEqual(snapshot.topEntries(1).getFirst().key(), iron, "largest entry");

        // The estimate must match a simulated insertion into the live handler for a plain vanilla container.
        long estimate = snapshot.insertable(iron, iron.getMaxStackSize());
        ItemStack probe = iron.toStack(PROBE_AMOUNT);
        long live = PROBE_AMOUNT - ItemHandlerHelper.insertItem(handler, probe, true).getCount();
        helper.assertValueEqual(estimate, live, "insertable estimate vs. simulated insertion");
        helper.assertValueEqual(snapshot.extractable(iron), (long) INSERTED_IRON, "extractable iron");

        helper.succeed();
    }

    /**
     * The insert estimate is an upper bound for restricted inventories: a shulker box (a sided vanilla container) has
     * room for 27 shulker boxes by slot math, but its insertion rules reject them. Unrestricted items still match a
     * simulated insert. This is why planning validates every candidate with a live simulate
     * ({@code docs/warehouse-system.md} §5).
     */
    @GameTest(template = EMPTY_7X5X7)
    public static void shulkerCapacityEstimate(GameTestHelper helper) {
        BlockPos boxPos = new BlockPos(3, BASE_Y, 3);
        helper.setBlock(boxPos, Blocks.SHULKER_BOX);
        IItemHandler handler = helper.getLevel()
                .getCapability(Capabilities.ItemHandler.BLOCK, helper.absolutePos(boxPos), Direction.SOUTH);
        if (handler == null)
            helper.fail("shulker box exposes no item handler", boxPos);

        InventorySnapshot<ItemKey> snapshot = ItemHandlerSnapshots.capture(handler);
        ItemKey shulker = ItemKey.of(Items.SHULKER_BOX);
        helper.assertValueEqual(snapshot.insertable(shulker, shulker.getMaxStackSize()), (long) CHEST_SLOTS,
                "slot math: one unstackable shulker box per slot");
        helper.assertValueEqual(simulatedInsert(handler, shulker), 0L, "the shulker box rejects shulker boxes");

        ItemKey iron = ItemKey.of(Items.IRON_INGOT);
        helper.assertValueEqual(snapshot.insertable(iron, iron.getMaxStackSize()), simulatedInsert(handler, iron),
                "unrestricted items match the simulated insert");
        helper.succeed();
    }

    /** ItemKey equality ignores count but not components, and persistence round-trips without ever throwing. */
    @GameTest(template = EMPTY_7X5X7)
    public static void itemKeyPersistence(GameTestHelper helper) {
        HolderLookup.Provider registries = helper.getLevel().registryAccess();

        ItemKey plain = ItemKey.of(new ItemStack(Items.DIAMOND_SWORD));
        ItemStack namedStack = new ItemStack(Items.DIAMOND_SWORD);
        namedStack.set(DataComponents.CUSTOM_NAME, Component.literal("Excalibur"));
        ItemKey named = ItemKey.of(namedStack);

        helper.assertFalse(plain.equals(named), "components must be part of the key");
        helper.assertValueEqual(ItemKey.of(new ItemStack(Items.IRON_INGOT, 37)), ItemKey.of(Items.IRON_INGOT),
                "count-less equality");
        helper.assertValueEqual(ItemKey.of(new ItemStack(Items.IRON_INGOT, 37)).hashCode(),
                ItemKey.of(Items.IRON_INGOT).hashCode(), "count-less hash");
        helper.assertTrue(ItemKey.fromStack(ItemStack.EMPTY).isEmpty(), "empty stack has no key");
        helper.assertTrue(named.matches(namedStack.copyWithCount(1)), "key matches its stack");
        helper.assertFalse(named.matches(new ItemStack(Items.DIAMOND_SWORD)), "key does not match other components");

        // toStack returns independent copies with any count
        ItemStack big = plain.toStack(LARGE_COUNT);
        helper.assertValueEqual(big.getCount(), LARGE_COUNT, "toStack count");
        big.set(DataComponents.CUSTOM_NAME, Component.literal("mutated"));
        helper.assertFalse(plain.matches(big), "mutating a copy must not change the key");
        helper.assertTrue(plain.matches(plain.toStack()), "key unchanged after mutating a copy");
        helper.assertTrue(plain.toStack(0).isEmpty(), "toStack(0) is empty");

        Tag saved = named.save(registries);
        Optional<ItemKey> loaded = ItemKey.load(registries, saved);
        helper.assertValueEqual(loaded, Optional.of(named), "round trip with components");

        CompoundTag parent = new CompoundTag();
        plain.saveTo(parent, "Key", registries);
        helper.assertValueEqual(ItemKey.loadFrom(parent, "Key", registries), Optional.of(plain), "saveTo/loadFrom");
        helper.assertTrue(ItemKey.loadFrom(parent, "Missing", registries).isEmpty(), "missing entry");

        // Invalid input never throws
        helper.assertTrue(ItemKey.load(registries, null).isEmpty(), "null tag");
        helper.assertTrue(ItemKey.load(registries, new CompoundTag()).isEmpty(), "empty tag");
        helper.assertTrue(ItemKey.load(registries, StringTag.valueOf("garbage")).isEmpty(), "wrong tag type");
        CompoundTag unknown = new CompoundTag();
        unknown.putString("id", Wareworks.ID + ":does_not_exist");
        helper.assertTrue(ItemKey.load(registries, unknown).isEmpty(), "unknown item id");

        helper.succeed();
    }

    /** The large template loads with its full floor and free space up to its top layer. */
    @GameTest(template = AISLE_16X10X7)
    public static void aisleTemplate(GameTestHelper helper) {
        int maxX = 15;
        int maxY = 10;
        int maxZ = 6;
        helper.assertBlockPresent(Blocks.SMOOTH_STONE, new BlockPos(0, FLOOR_Y, 0));
        helper.assertBlockPresent(Blocks.SMOOTH_STONE, new BlockPos(maxX, FLOOR_Y, maxZ));
        helper.assertBlockPresent(Blocks.SMOOTH_STONE, new BlockPos(maxX, FLOOR_Y, 0));
        helper.assertBlockPresent(Blocks.SMOOTH_STONE, new BlockPos(0, FLOOR_Y, maxZ));
        helper.assertBlockState(new BlockPos(maxX, maxY, maxZ), state -> state.isAir(), () -> "top layer must be free");
        helper.assertBlockState(new BlockPos(1, BASE_Y, 3), state -> state.isAir(), () -> "aisle start must be free");
        helper.succeed();
    }

    /** Server config is loaded on the test server and the creative tab is registered. */
    @GameTest(template = EMPTY_7X5X7)
    public static void foundationRegistries(GameTestHelper helper) {
        helper.assertTrue(WareworksConfig.isServerConfigLoaded(), "server config must be loaded on the server");
        int maxAisleLength = WareworksConfig.maxAisleLength();
        helper.assertTrue(maxAisleLength >= 1, "maxAisleLength must be positive: " + maxAisleLength);
        helper.assertValueEqual(WareworksConfig.maxAisleLength(), WareworksConfig.SERVER.maxAisleLength.get(),
                "safe getter reads the loaded value");
        helper.assertTrue(BuiltInRegistries.CREATIVE_MODE_TAB.containsKey(WareworksCreativeTabs.BASE_KEY),
                "creative tab " + WareworksCreativeTabs.BASE_KEY.location() + " is not registered");
        helper.succeed();
    }

    /** Amount of {@code key} a simulated insertion of {@link #PROBE_AMOUNT} items into all slots would accept. */
    private static long simulatedInsert(IItemHandler handler, ItemKey key) {
        return PROBE_AMOUNT - ItemHandlerHelper.insertItem(handler, key.toStack(PROBE_AMOUNT), true).getCount();
    }

    private static void insertAll(GameTestHelper helper, IItemHandler handler, ItemStack stack) {
        ItemStack rest = ItemHandlerHelper.insertItem(handler, stack, false);
        helper.assertTrue(rest.isEmpty(), "inventory rejected " + rest);
    }
}
