package dev.wareworks.gametest;

import java.util.Optional;

import dev.wareworks.Wareworks;
import dev.wareworks.config.WareworksConfig;
import dev.wareworks.content.fluid.FluidContainers;
import dev.wareworks.content.fluid.FluidKey;
import dev.wareworks.content.fluid.FluidTypeSummaries;
import dev.wareworks.content.item.ItemHandlerSnapshots;
import dev.wareworks.content.item.ItemKey;
import dev.wareworks.core.inventory.CapacityMath;
import dev.wareworks.core.inventory.InventorySnapshot;
import dev.wareworks.core.storage.FluidBayTier;
import dev.wareworks.registry.WareworksCreativeTabs;
import net.minecraft.core.BlockPos;
import net.minecraft.core.Direction;
import net.minecraft.core.HolderLookup;
import net.minecraft.core.component.DataComponents;
import net.minecraft.core.registries.BuiltInRegistries;
import net.minecraft.gametest.framework.GameTest;
import net.minecraft.gametest.framework.GameTestHelper;
import net.minecraft.nbt.CompoundTag;
import net.minecraft.nbt.StringTag;
import net.minecraft.nbt.Tag;
import net.minecraft.network.chat.Component;
import net.minecraft.world.item.Item;
import net.minecraft.world.item.ItemStack;
import net.minecraft.world.item.Items;
import net.minecraft.world.level.block.Blocks;
import net.minecraft.world.level.material.Fluids;
import net.neoforged.neoforge.capabilities.Capabilities;
import net.neoforged.neoforge.fluids.FluidStack;
import net.neoforged.neoforge.fluids.FluidType;
import net.neoforged.neoforge.fluids.capability.IFluidHandler.FluidAction;
import net.neoforged.neoforge.fluids.capability.IFluidHandlerItem;
import net.neoforged.neoforge.gametest.GameTestHolder;
import net.neoforged.neoforge.gametest.PrefixGameTestTemplate;
import net.neoforged.neoforge.items.IItemHandler;
import net.neoforged.neoforge.items.ItemHandlerHelper;

/**
 * Foundation GameTests: prove that the GameTest pipeline, the structure templates and the foundation classes work in a
 * real server.
 * <p>
 * Templates live in {@code data/wareworks/structure/<name>.nbt} and are generated by {@code scripts/gen_structures.py}.
 * They contain only a floor: template layer 0 is test-relative {@code y = 1} ({@link #FLOOR_Y}); test-relative
 * {@code y = 0} is the structure block layer and must never be built on.
 * <p>
 * Test names are the lowercased method names ({@code @PrefixGameTestTemplate(false)} drops the class prefix from both
 * template path and test name). Run one in a dev client or server with {@code /test run <name>}.
 */
@GameTestHolder(Wareworks.ID)
@PrefixGameTestTemplate(false)
public final class WareworksGameTests {
    /** 7 x 5 x 7 floor plate for small single-block tests. */
    public static final String EMPTY_7X5X7 = "empty_7x5x7";
    /**
     * 16 x 10 x 7 floor plate for aisle tests: an aisle along +X at z = 3 (controller x = 0, dock x = 1, up to 14 rails
     * x = 2..15), racks and inventories on both sides at z = 1..2 and z = 4..5, mast levels up to 6 above the dock.
     */
    public static final String AISLE_16X10X7 = "aisle_16x10x7";
    /**
     * 48 x 5 x 3 floor strip for long rail lines: a dock at x = 0, z = 1 with up to 47 rails x = 1..47 (rail cap tests).
     */
    public static final String RAIL_LINE_48X5X3 = "rail_line_48x5x3";
    /**
     * 16 x 10 x 13 floor plate with room for two parallel aisles along +X: the {@link #AISLE_16X10X7} layout at z = 3 and
     * again at z = 9 (side-by-side comparisons, e.g. throughput at different speeds).
     */
    public static final String AISLE_PAIR_16X10X13 = "aisle_pair_16x10x13";

    /** Test-relative y of the template floor. */
    public static final int FLOOR_Y = 1;
    /** First free layer above the floor. */
    public static final int BASE_Y = 2;

    /**
     * Bound of a warehouse interface's update tag in NBT size accounting ({@code Tag#sizeInBytes}) without reservations:
     * the goggle summary (at most 3 item ids and counts) and the aisle assignment. Almost every interface of a rack wall is
     * in this state; syncing item components would exceed it by orders of magnitude.
     */
    public static final int MAX_INTERFACE_SYNC_BYTES = 2048;
    /**
     * Bound of a warehouse interface's update tag with the largest reservation summary (2 incoming and 2 outgoing item
     * types with long ids). Only the locations of running jobs have reservations. The accounting counts 36 + 2 bytes per
     * character for every string, far more than is sent ({@code docs/warehouse-system.md} §3.1.1).
     */
    public static final int MAX_RESERVED_INTERFACE_SYNC_BYTES = 4096;
    /**
     * Bound of a <b>rack bay</b>'s update tag in NBT size accounting ({@code Tag#sizeInBytes}) in the state almost
     * every bay of a rack wall is in: one item id, one count and the aisle assignment, with no filter and no
     * reservations (M28, {@code warehouse-system.md} §3.8, ADR-045).
     * <p>
     * It gets a bound of its own, and a tighter one than the interface's, for one reason: a bay is the first block of
     * this mod that syncs its <b>contents</b> on every change and without any throttle, because its front has to be
     * right for a player walking past with no goggles on. That is affordable exactly as long as the tag stays an item
     * id and an int — syncing an {@code ItemKey} here would put a shulker box of written books into every chunk
     * packet of a rack wall, which is the regression the warehouse interface already shipped once.
     */
    public static final int MAX_RACK_BAY_SYNC_BYTES = 1024;
    /**
     * Bound of a rack bay's update tag in the worst case a warehouse can produce: a store filter, a storage priority,
     * the widest address with the longest aisle name, and the largest reservation summary of a location with a job
     * running at it. Only the bays of running jobs ever reach it.
     */
    public static final int MAX_RESERVED_RACK_BAY_SYNC_BYTES = 4096;
    /**
     * Bound of a <b>fluid bay</b>'s update tag in NBT size accounting ({@code Tag#sizeInBytes}) in the state every bay
     * of a tank wall is in: one fluid id and one amount of millibuckets (M30, issue #21,
     * {@code warehouse-system.md} §3.9).
     * <p>
     * It is the rack bay's bound for the rack bay's reason — a bay syncs its contents on every change and without any
     * throttle, because its level <b>is</b> the readout and has to be right for a player walking past with no goggles
     * on — and it is affordable exactly as long as the tag stays an id and an int. A {@code FluidKey} here would put a
     * named potion fluid's whole component patch into every chunk packet of a tank wall.
     */
    public static final int MAX_FLUID_BAY_SYNC_BYTES = 1024;

    private static final int CHEST_SLOTS = 27;
    private static final int INSERTED_IRON = 100;
    private static final int LARGE_COUNT = 150;
    private static final int PROBE_AMOUNT = 100_000;

    private WareworksGameTests() {
    }

    /** Infrastructure smoke test: a chest placed via the helper is readable through the item capability. */
    @GameTest(template = EMPTY_7X5X7)
    public static void chestSnapshot(GameTestHelper helper) {
        BlockPos chestPos = new BlockPos(3, BASE_Y, 3);
        helper.setBlock(chestPos, Blocks.CHEST);
        helper.assertBlockPresent(Blocks.CHEST, chestPos);

        IItemHandler handler = helper.getLevel()
                .getCapability(Capabilities.ItemHandler.BLOCK, helper.absolutePos(chestPos), null);
        if (handler == null)
            helper.fail("chest exposes no item handler", chestPos);

        ItemStack named = new ItemStack(Items.IRON_INGOT);
        named.set(DataComponents.CUSTOM_NAME, Component.literal("Wareworks test ingot"));
        insertAll(helper, handler, new ItemStack(Items.IRON_INGOT, INSERTED_IRON));
        insertAll(helper, handler, named.copy());

        InventorySnapshot<ItemKey> snapshot = ItemHandlerSnapshots.capture(handler);
        ItemKey iron = ItemKey.of(Items.IRON_INGOT);
        helper.assertValueEqual(snapshot.totalSlots(), CHEST_SLOTS, "total slots");
        helper.assertValueEqual(snapshot.usedSlots(), 3, "used slots (64 + 36 plain, 1 named)");
        helper.assertValueEqual(snapshot.count(iron), (long) INSERTED_IRON, "plain iron count");
        helper.assertValueEqual(snapshot.count(ItemKey.of(named)), 1L, "named iron count");
        helper.assertValueEqual(snapshot.keys().size(), 2, "distinct keys (components matter)");
        helper.assertValueEqual(snapshot.topEntries(1).getFirst().key(), iron, "largest entry");

        // The estimate must match a simulated insertion into the live handler for a plain vanilla container.
        long estimate = snapshot.insertable(iron, iron.getMaxStackSize());
        ItemStack probe = iron.toStack(PROBE_AMOUNT);
        long live = PROBE_AMOUNT - ItemHandlerHelper.insertItem(handler, probe, true).getCount();
        helper.assertValueEqual(estimate, live, "insertable estimate vs. simulated insertion");
        helper.assertValueEqual(snapshot.extractable(iron), (long) INSERTED_IRON, "extractable iron");

        helper.succeed();
    }

    /**
     * The insert estimate is an upper bound for restricted inventories: a shulker box (a sided vanilla container) has
     * room for 27 shulker boxes by slot math, but its insertion rules reject them. Unrestricted items still match a
     * simulated insert. This is why planning validates every candidate with a live simulate
     * ({@code docs/warehouse-system.md} §5).
     */
    @GameTest(template = EMPTY_7X5X7)
    public static void shulkerCapacityEstimate(GameTestHelper helper) {
        BlockPos boxPos = new BlockPos(3, BASE_Y, 3);
        helper.setBlock(boxPos, Blocks.SHULKER_BOX);
        IItemHandler handler = helper.getLevel()
                .getCapability(Capabilities.ItemHandler.BLOCK, helper.absolutePos(boxPos), Direction.SOUTH);
        if (handler == null)
            helper.fail("shulker box exposes no item handler", boxPos);

        InventorySnapshot<ItemKey> snapshot = ItemHandlerSnapshots.capture(handler);
        ItemKey shulker = ItemKey.of(Items.SHULKER_BOX);
        helper.assertValueEqual(snapshot.insertable(shulker, shulker.getMaxStackSize()), (long) CHEST_SLOTS,
                "slot math: one unstackable shulker box per slot");
        helper.assertValueEqual(simulatedInsert(handler, shulker), 0L, "the shulker box rejects shulker boxes");

        ItemKey iron = ItemKey.of(Items.IRON_INGOT);
        helper.assertValueEqual(snapshot.insertable(iron, iron.getMaxStackSize()), simulatedInsert(handler, iron),
                "unrestricted items match the simulated insert");
        helper.succeed();
    }

    /**
     * The world facts the drawer fix rests on. {@link CapacityMath#STACK_SIZE_CEILING} mirrors
     * {@code Item.ABSOLUTE_MAX_STACK_SIZE}, which the pure core layer cannot see, and a real vanilla container reports
     * exactly that per slot. Both together are the cost bound: a chest full of a 16-stacking item still answers an
     * exact 0 and provokes no live simulate, while only a slot limit <b>above</b> the ceiling (a drawer from a storage
     * mod) can answer {@link CapacityMath#UNKNOWN_CAPACITY}.
     */
    @GameTest(template = EMPTY_7X5X7)
    public static void stackSizeCeiling(GameTestHelper helper) {
        helper.assertValueEqual(CapacityMath.STACK_SIZE_CEILING, Item.ABSOLUTE_MAX_STACK_SIZE,
                "the core mirror of Item.ABSOLUTE_MAX_STACK_SIZE");

        BlockPos chestPos = new BlockPos(3, BASE_Y, 3);
        helper.setBlock(chestPos, Blocks.CHEST);
        IItemHandler handler = helper.getLevel()
                .getCapability(Capabilities.ItemHandler.BLOCK, helper.absolutePos(chestPos), null);
        if (handler == null)
            helper.fail("chest exposes no item handler", chestPos);
        helper.assertValueEqual(handler.getSlotLimit(0), CapacityMath.STACK_SIZE_CEILING,
                "a vanilla container's slot limit is never above the ceiling");

        ItemKey pearl = ItemKey.of(Items.ENDER_PEARL);
        for (int slot = 0; slot < CHEST_SLOTS; slot++)
            insertAll(helper, handler, pearl.toStack(pearl.getMaxStackSize()));
        InventorySnapshot<ItemKey> snapshot = ItemHandlerSnapshots.capture(handler);
        helper.assertValueEqual(snapshot.insertable(pearl, pearl.getMaxStackSize()), 0L,
                "a full ordinary container is exactly full, not unknown");
        helper.assertValueEqual(simulatedInsert(handler, pearl), 0L, "and the live handler agrees");
        helper.succeed();
    }

    /** ItemKey equality ignores count but not components, and persistence round-trips without ever throwing. */
    @GameTest(template = EMPTY_7X5X7)
    public static void itemKeyPersistence(GameTestHelper helper) {
        HolderLookup.Provider registries = helper.getLevel().registryAccess();

        ItemKey plain = ItemKey.of(new ItemStack(Items.DIAMOND_SWORD));
        ItemStack namedStack = new ItemStack(Items.DIAMOND_SWORD);
        namedStack.set(DataComponents.CUSTOM_NAME, Component.literal("Excalibur"));
        ItemKey named = ItemKey.of(namedStack);

        helper.assertFalse(plain.equals(named), "components must be part of the key");
        helper.assertValueEqual(ItemKey.of(new ItemStack(Items.IRON_INGOT, 37)), ItemKey.of(Items.IRON_INGOT),
                "count-less equality");
        helper.assertValueEqual(ItemKey.of(new ItemStack(Items.IRON_INGOT, 37)).hashCode(),
                ItemKey.of(Items.IRON_INGOT).hashCode(), "count-less hash");
        helper.assertTrue(ItemKey.fromStack(ItemStack.EMPTY).isEmpty(), "empty stack has no key");
        helper.assertTrue(named.matches(namedStack.copyWithCount(1)), "key matches its stack");
        helper.assertFalse(named.matches(new ItemStack(Items.DIAMOND_SWORD)), "key does not match other components");

        // toStack returns independent copies with any count
        ItemStack big = plain.toStack(LARGE_COUNT);
        helper.assertValueEqual(big.getCount(), LARGE_COUNT, "toStack count");
        big.set(DataComponents.CUSTOM_NAME, Component.literal("mutated"));
        helper.assertFalse(plain.matches(big), "mutating a copy must not change the key");
        helper.assertTrue(plain.matches(plain.toStack()), "key unchanged after mutating a copy");
        helper.assertTrue(plain.toStack(0).isEmpty(), "toStack(0) is empty");

        Tag saved = named.save(registries);
        Optional<ItemKey> loaded = ItemKey.load(registries, saved);
        helper.assertValueEqual(loaded, Optional.of(named), "round trip with components");

        CompoundTag parent = new CompoundTag();
        plain.saveTo(parent, "Key", registries);
        helper.assertValueEqual(ItemKey.loadFrom(parent, "Key", registries), Optional.of(plain), "saveTo/loadFrom");
        helper.assertTrue(ItemKey.loadFrom(parent, "Missing", registries).isEmpty(), "missing entry");

        // Invalid input never throws
        helper.assertTrue(ItemKey.load(registries, null).isEmpty(), "null tag");
        helper.assertTrue(ItemKey.load(registries, new CompoundTag()).isEmpty(), "empty tag");
        helper.assertTrue(ItemKey.load(registries, StringTag.valueOf("garbage")).isEmpty(), "wrong tag type");
        CompoundTag unknown = new CompoundTag();
        unknown.putString("id", Wareworks.ID + ":does_not_exist");
        helper.assertTrue(ItemKey.load(registries, unknown).isEmpty(), "unknown item id");

        helper.succeed();
    }

    /**
     * The fluid foundation of M30 (issue #21), in the one place a Minecraft constant can be read at all: the pure
     * {@link FluidBayTier#MILLIBUCKETS_PER_BUCKET} really is {@code FluidType.BUCKET_VOLUME}, and the configured
     * capacities really come out as the issue's table. This is {@link #stackSizeCeiling}'s argument for fluids — the
     * {@code core} layer cannot import a NeoForge class, so the mirror is asserted here rather than remembered.
     */
    @GameTest(template = EMPTY_7X5X7)
    public static void fluidBayFoundation(GameTestHelper helper) {
        helper.assertValueEqual(FluidBayTier.MILLIBUCKETS_PER_BUCKET, FluidType.BUCKET_VOLUME,
                "the core mirror of FluidType.BUCKET_VOLUME");

        helper.assertValueEqual(WareworksConfig.fluidBayBuckets(FluidBayTier.COPPER), 64, "copper fluid bay buckets");
        helper.assertValueEqual(WareworksConfig.fluidBayBuckets(FluidBayTier.BRASS), 256, "brass fluid bay buckets");
        helper.assertValueEqual(WareworksConfig.fluidBayCapacity(FluidBayTier.COPPER), 64L * FluidType.BUCKET_VOLUME,
                "copper fluid bay capacity in mB");
        helper.assertValueEqual(WareworksConfig.fluidBayCapacity(FluidBayTier.BRASS), 256L * FluidType.BUCKET_VOLUME,
                "brass fluid bay capacity in mB");
        helper.assertTrue(WareworksConfig.fluidBayPipeExtraction(), "pipes may draw off a fluid bay by default");

        // A bay with less than a whole bucket of room takes nothing from a bucket - the issue's one corrected claim.
        helper.assertValueEqual(FluidBayTier.wholeContainers(FluidType.BUCKET_VOLUME, FluidType.BUCKET_VOLUME - 1), 0,
                "999 mB of room takes no bucket");
        helper.assertValueEqual(
                FluidBayTier.wholeContainers(FluidType.BUCKET_VOLUME,
                        WareworksConfig.fluidBayCapacity(FluidBayTier.COPPER)),
                64, "an empty copper bay takes 64 buckets");

        // The registry id round trip the bay's update tag is built on, and the two ids that must never read back.
        helper.assertValueEqual(FluidTypeSummaries.fluidId(Fluids.LAVA), "minecraft:lava", "fluid id");
        helper.assertValueEqual(FluidTypeSummaries.fluidById("minecraft:lava"), Optional.of(Fluids.LAVA),
                "fluid by id");
        helper.assertTrue(FluidTypeSummaries.fluidById("minecraft:empty").isEmpty(), "the empty fluid is no fluid");
        helper.assertTrue(FluidTypeSummaries.fluidById("not a resource location").isEmpty(), "unparsable id");
        helper.assertTrue(FluidTypeSummaries.fluidById(Wareworks.ID + ":does_not_exist").isEmpty(), "unknown fluid id");
        helper.succeed();
    }

    /**
     * {@link FluidKey} equality ignores the amount but not the components, a mutated source stack cannot change a key
     * that was built from it, and persistence round-trips without ever throwing — including the trap this class exists
     * for, that {@code FluidStack.save} throws on an empty stack.
     */
    @GameTest(template = EMPTY_7X5X7)
    public static void fluidKeyPersistence(GameTestHelper helper) {
        HolderLookup.Provider registries = helper.getLevel().registryAccess();

        FluidKey lava = FluidKey.of(Fluids.LAVA);
        FluidStack namedStack = new FluidStack(Fluids.WATER, FluidType.BUCKET_VOLUME);
        namedStack.set(DataComponents.CUSTOM_NAME, Component.literal("Holy Water"));
        FluidKey named = FluidKey.of(namedStack);

        helper.assertFalse(named.equals(FluidKey.of(Fluids.WATER)), "components must be part of the key");
        helper.assertValueEqual(FluidKey.of(new FluidStack(Fluids.LAVA, PROBE_AMOUNT)), lava, "amount-less equality");
        helper.assertValueEqual(FluidKey.of(new FluidStack(Fluids.LAVA, PROBE_AMOUNT)).hashCode(), lava.hashCode(),
                "amount-less hash");
        helper.assertTrue(FluidKey.fromStack(FluidStack.EMPTY).isEmpty(), "empty stack has no key");
        helper.assertTrue(FluidKey.fromStack(null).isEmpty(), "no stack, no key");
        helper.assertTrue(lava.matches(new FluidStack(Fluids.LAVA, 1)), "key matches its fluid at any amount");
        helper.assertFalse(lava.matches(named.toStack()), "key does not match another fluid");
        helper.assertFalse(named.matches(new FluidStack(Fluids.WATER, 1)), "key does not match other components");

        // A FluidStack is mutable and handlers hand out live ones: a key built from one must not follow it.
        FluidStack live = new FluidStack(Fluids.LAVA, FluidType.BUCKET_VOLUME);
        FluidKey fromLive = FluidKey.of(live);
        live.setAmount(7);
        live.set(DataComponents.CUSTOM_NAME, Component.literal("mutated"));
        helper.assertValueEqual(fromLive, lava, "mutating the source must not change the key");
        helper.assertValueEqual(fromLive.hashCode(), lava.hashCode(), "nor its hash");
        helper.assertFalse(fromLive.matches(live), "the mutated stack is no longer this key");

        // toStack hands out independent copies at any amount, and nothing it hands out can reach back in.
        FluidStack copy = lava.toStack(PROBE_AMOUNT);
        helper.assertValueEqual(copy.getAmount(), PROBE_AMOUNT, "toStack amount");
        copy.set(DataComponents.CUSTOM_NAME, Component.literal("mutated"));
        helper.assertFalse(lava.matches(copy), "mutating a copy must not change the key");
        helper.assertTrue(lava.matches(lava.toStack()), "key unchanged after mutating a copy");
        helper.assertTrue(lava.toStack(0).isEmpty(), "toStack(0) is empty");
        helper.assertTrue(lava.toStack(-1).isEmpty(), "toStack of a negative amount is empty");
        helper.assertValueEqual(lava.toStack().getAmount(), 1, "the key's own stack holds 1 mB");

        // The trap: the obvious persistence call throws, which is why FluidKey has its own and can never be empty.
        boolean threw = false;
        try {
            FluidStack.EMPTY.save(registries);
        } catch (IllegalStateException expected) {
            threw = true;
        }
        helper.assertTrue(threw, "FluidStack.save must throw on an empty stack");

        Tag saved = named.save(registries);
        helper.assertValueEqual(FluidKey.load(registries, saved), Optional.of(named), "round trip with components");
        helper.assertValueEqual(FluidKey.load(registries, lava.save(registries)), Optional.of(lava),
                "round trip without components");

        CompoundTag parent = new CompoundTag();
        lava.saveTo(parent, "Fluid", registries);
        helper.assertValueEqual(FluidKey.loadFrom(parent, "Fluid", registries), Optional.of(lava), "saveTo/loadFrom");
        helper.assertTrue(FluidKey.loadFrom(parent, "Missing", registries).isEmpty(), "missing entry");

        // Invalid input never throws
        helper.assertTrue(FluidKey.load(registries, null).isEmpty(), "null tag");
        helper.assertTrue(FluidKey.load(registries, new CompoundTag()).isEmpty(), "empty tag");
        helper.assertTrue(FluidKey.load(registries, StringTag.valueOf("garbage")).isEmpty(), "wrong tag type");
        CompoundTag unknown = new CompoundTag();
        unknown.putString("id", Wareworks.ID + ":does_not_exist");
        helper.assertTrue(FluidKey.load(registries, unknown).isEmpty(), "unknown fluid id");
        CompoundTag emptyFluid = new CompoundTag();
        emptyFluid.putString("id", "minecraft:empty");
        helper.assertTrue(FluidKey.load(registries, emptyFluid).isEmpty(), "the empty fluid is refused on load");

        // ORDER depends only on values, so it is the same after a restart - two fresh keys sort the same way twice.
        helper.assertTrue(FluidKey.ORDER.compare(lava, FluidKey.of(Fluids.WATER)) < 0, "lava sorts before water");
        helper.assertTrue(FluidKey.ORDER.compare(FluidKey.of(Fluids.WATER), named) < 0,
                "a plain key sorts before the same fluid carrying components");
        helper.assertValueEqual(FluidKey.ORDER.compare(lava, FluidKey.of(Fluids.LAVA)), 0, "equal keys tie");
        helper.assertValueEqual(FluidKey.ORDER.compare(FluidKey.of(namedStack), named), 0,
                "two constructions of one key tie, whatever the JVM identity hash of the fluid is");
        helper.succeed();
    }

    /**
     * {@link FluidContainers}: the capability is the only authority, a container is drained to empty or refused and
     * filled to full or refused, and every one of the four traps the class doc names is really there in the game.
     */
    @GameTest(template = EMPTY_7X5X7)
    public static void fluidContainerRules(GameTestHelper helper) {
        ItemKey filledBucket = ItemKey.of(Items.LAVA_BUCKET);
        ItemKey emptyBucket = ItemKey.of(Items.BUCKET);
        FluidKey lava = FluidKey.of(Fluids.LAVA);
        FluidKey water = FluidKey.of(Fluids.WATER);
        int bucket = FluidType.BUCKET_VOLUME;

        // What carries fluid, and what only looks as if it did.
        helper.assertValueEqual(FluidContainers.contents(filledBucket),
                Optional.of(new FluidContainers.Contents(lava, bucket)), "a lava bucket carries a bucket of lava");
        helper.assertTrue(FluidContainers.carriesFluid(filledBucket), "a lava bucket is a filled container");
        helper.assertTrue(FluidContainers.contents(emptyBucket).isEmpty(), "an empty bucket carries nothing");
        helper.assertTrue(FluidContainers.isEmptyContainer(emptyBucket), "an empty bucket is an empty container");
        helper.assertFalse(FluidContainers.isEmptyContainer(filledBucket), "a filled bucket is not an empty one");
        helper.assertFalse(FluidContainers.isEmptyContainer(ItemKey.of(Items.COBBLESTONE)),
                "cobblestone is no container at all");
        helper.assertFalse(FluidContainers.carriesFluid(ItemKey.of(Items.COBBLESTONE)), "nor does it carry fluid");

        // The documented consequence of "the capability is the only authority": a bottle is not a container.
        helper.assertFalse(FluidContainers.isEmptyContainer(ItemKey.of(Items.GLASS_BOTTLE)),
                "a glass bottle has no fluid capability, so it is no container");
        helper.assertTrue(FluidContainers.contents(ItemKey.of(Items.POTION)).isEmpty(),
                "neither has a water bottle");

        // Trap 1: every operation needs a stack of exactly one, and a census must read per item rather than per stack.
        ItemStack sixteen = new ItemStack(Items.LAVA_BUCKET, 16);
        IFluidHandlerItem raw = sixteen.getCapability(Capabilities.FluidHandler.ITEM);
        if (raw == null)
            helper.fail("a lava bucket must answer the item fluid capability");
        helper.assertTrue(raw.drain(Integer.MAX_VALUE, FluidAction.SIMULATE).isEmpty(),
                "a handler answers nothing at all for a stack of 16 - the trap this class absorbs");
        helper.assertValueEqual(FluidContainers.contentsOf(sixteen),
                Optional.of(new FluidContainers.Contents(lava, bucket)), "one item of the stack, never the stack");
        helper.assertValueEqual(sixteen.getCount(), 16, "reading a stack must not change it");
        helper.assertTrue(FluidContainers.contentsOf(ItemStack.EMPTY).isEmpty(), "an empty stack carries nothing");
        helper.assertTrue(FluidContainers.contentsOf(null).isEmpty(), "no stack, no fluid");

        // Trap 3 and 4: a real drain is the only way to learn the emptied container, and it is a different item.
        Optional<FluidContainers.Drained> maybeDrained = FluidContainers.drained(filledBucket);
        if (maybeDrained.isEmpty())
            helper.fail("a lava bucket must be drainable");
        FluidContainers.Drained drained = maybeDrained.orElseThrow();
        helper.assertValueEqual(drained.fluid(), lava, "the fluid that came out");
        helper.assertValueEqual(drained.millibuckets(), bucket, "the whole contents, in one go");
        helper.assertValueEqual(drained.emptied(), emptyBucket, "the bucket that is left");
        helper.assertValueEqual(FluidContainers.contents(filledBucket),
                Optional.of(new FluidContainers.Contents(lava, bucket)), "the probe was ours, so nothing moved");
        helper.assertTrue(FluidContainers.drained(emptyBucket).isEmpty(), "an empty bucket yields no drain");
        helper.assertTrue(FluidContainers.drained(ItemKey.of(Items.COBBLESTONE)).isEmpty(), "nor does cobblestone");

        // The simulated drain really does lie about the container, which is why the real one is run.
        ItemStack probe = filledBucket.toStack();
        IFluidHandlerItem simulated = probe.getCapability(Capabilities.FluidHandler.ITEM);
        if (simulated == null)
            helper.fail("a lava bucket must answer the item fluid capability");
        simulated.drain(Integer.MAX_VALUE, FluidAction.SIMULATE);
        helper.assertTrue(filledBucket.matches(simulated.getContainer()),
                "after a simulated drain getContainer() is still the FILLED bucket");

        // Filled to full or refused, with the capacity measured rather than looked up.
        Optional<FluidContainers.Filled> maybeFilled = FluidContainers.filled(emptyBucket, lava);
        if (maybeFilled.isEmpty())
            helper.fail("an empty bucket must take lava");
        FluidContainers.Filled filled = maybeFilled.orElseThrow();
        helper.assertValueEqual(filled.filled(), filledBucket, "a bucket of lava");
        helper.assertValueEqual(filled.millibuckets(), bucket, "a measured bucket, not a constant");
        helper.assertValueEqual(FluidContainers.filled(emptyBucket, water).map(FluidContainers.Filled::filled),
                Optional.of(ItemKey.of(Items.WATER_BUCKET)), "and a bucket of water");
        helper.assertTrue(FluidContainers.filled(filledBucket, lava).isEmpty(), "only empty containers are filled");
        helper.assertTrue(FluidContainers.filled(ItemKey.of(Items.COBBLESTONE), lava).isEmpty(),
                "cobblestone takes no lava");
        helper.assertTrue(FluidContainers.filled(emptyBucket, FluidKey.of(Fluids.FLOWING_LAVA)).isEmpty(),
                "a container that hands back a different fluid key than it took is refused");

        // The refusals no vanilla container produces, stated through the rule itself.
        helper.assertTrue(
                FluidContainers.judgeDrain(lava, bucket, lava.toStack(bucket), ItemStack.EMPTY).isEmpty(),
                "a consumable container, whose empty form is nothing, is refused");
        helper.assertTrue(FluidContainers.judgeDrain(lava, bucket, lava.toStack(bucket), null).isEmpty(),
                "and so is a handler that answers no container at all");
        helper.assertTrue(
                FluidContainers.judgeDrain(lava, bucket, lava.toStack(bucket), emptyBucket.toStack(2)).isEmpty(),
                "one container in, one container out");
        helper.assertTrue(
                FluidContainers.judgeDrain(lava, 5 * bucket, lava.toStack(bucket), emptyBucket.toStack()).isEmpty(),
                "a per-call cap that gives back less than the whole contents is refused, never a partial drain");
        helper.assertTrue(
                FluidContainers.judgeDrain(lava, bucket, water.toStack(bucket), emptyBucket.toStack()).isEmpty(),
                "a drain answering with another fluid is refused");
        helper.assertTrue(FluidContainers.judgeDrain(lava, bucket, lava.toStack(bucket), filledBucket.toStack())
                .isEmpty(), "a container that is not empty afterwards is refused");
        helper.assertValueEqual(
                FluidContainers.judgeDrain(lava, bucket, lava.toStack(bucket), emptyBucket.toStack()),
                Optional.of(new FluidContainers.Drained(lava, bucket, emptyBucket)), "and this is the accepted shape");

        helper.assertTrue(FluidContainers.judgeFill(lava, bucket, bucket - 1, filledBucket.toStack()).isEmpty(),
                "a fill that took less than the whole capacity is refused, never a partial fill");
        helper.assertTrue(FluidContainers.judgeFill(lava, bucket, bucket, ItemStack.EMPTY).isEmpty(),
                "a fill that leaves no container is refused");
        helper.assertTrue(FluidContainers.judgeFill(lava, bucket, bucket, emptyBucket.toStack()).isEmpty(),
                "a container that is still empty afterwards is refused");
        helper.assertValueEqual(FluidContainers.judgeFill(lava, bucket, bucket, filledBucket.toStack()),
                Optional.of(new FluidContainers.Filled(filledBucket, bucket)), "and this is the accepted shape");
        helper.succeed();
    }

    /** The large template loads with its full floor and free space up to its top layer. */
    @GameTest(template = AISLE_16X10X7)
    public static void aisleTemplate(GameTestHelper helper) {
        int maxX = 15;
        int maxY = 10;
        int maxZ = 6;
        helper.assertBlockPresent(Blocks.SMOOTH_STONE, new BlockPos(0, FLOOR_Y, 0));
        helper.assertBlockPresent(Blocks.SMOOTH_STONE, new BlockPos(maxX, FLOOR_Y, maxZ));
        helper.assertBlockPresent(Blocks.SMOOTH_STONE, new BlockPos(maxX, FLOOR_Y, 0));
        helper.assertBlockPresent(Blocks.SMOOTH_STONE, new BlockPos(0, FLOOR_Y, maxZ));
        helper.assertBlockState(new BlockPos(maxX, maxY, maxZ), state -> state.isAir(), () -> "top layer must be free");
        helper.assertBlockState(new BlockPos(1, BASE_Y, 3), state -> state.isAir(), () -> "aisle start must be free");
        helper.succeed();
    }

    /** Server config is loaded on the test server and the creative tab is registered. */
    @GameTest(template = EMPTY_7X5X7)
    public static void foundationRegistries(GameTestHelper helper) {
        helper.assertTrue(WareworksConfig.isServerConfigLoaded(), "server config must be loaded on the server");
        int maxAisleLength = WareworksConfig.maxAisleLength();
        helper.assertTrue(maxAisleLength >= 1, "maxAisleLength must be positive: " + maxAisleLength);
        helper.assertValueEqual(WareworksConfig.maxAisleLength(), WareworksConfig.SERVER.maxAisleLength.get(),
                "safe getter reads the loaded value");
        helper.assertTrue(BuiltInRegistries.CREATIVE_MODE_TAB.containsKey(WareworksCreativeTabs.BASE_KEY),
                "creative tab " + WareworksCreativeTabs.BASE_KEY.location() + " is not registered");
        helper.succeed();
    }

    /** Amount of {@code key} a simulated insertion of {@link #PROBE_AMOUNT} items into all slots would accept. */
    private static long simulatedInsert(IItemHandler handler, ItemKey key) {
        return PROBE_AMOUNT - ItemHandlerHelper.insertItem(handler, key.toStack(PROBE_AMOUNT), true).getCount();
    }

    private static void insertAll(GameTestHelper helper, IItemHandler handler, ItemStack stack) {
        ItemStack rest = ItemHandlerHelper.insertItem(handler, stack, false);
        helper.assertTrue(rest.isEmpty(), "inventory rejected " + rest);
    }
}
