package dev.wareworks.data;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertTrue;
import static org.junit.jupiter.api.Assertions.fail;

import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.Set;
import java.util.TreeSet;
import java.util.regex.Matcher;
import java.util.regex.Pattern;

import org.junit.jupiter.api.Test;

import dev.wareworks.core.production.PlanRefusal;

/**
 * English lang is generated by {@code runData}; German is hand-written. Every generated key must have a German
 * translation with the same format placeholders, and German must not contain stale keys.
 * <p>
 * Runs without Minecraft: it only reads the two flat JSON files. If it fails after adding lang entries, run
 * {@code ./gradlew runData} and update {@code de_de.json}.
 */
class LangConsistencyTest {
    private static final Path GENERATED_EN_US = Path.of("src/generated/resources/assets/wareworks/lang/en_us.json");
    private static final Path HAND_WRITTEN_DE_DE = Path.of("src/main/resources/assets/wareworks/lang/de_de.json");
    private static final Path HAND_WRITTEN_EN_US = Path.of("src/main/resources/assets/wareworks/lang/en_us.json");

    private static final Pattern STRING = Pattern.compile("\"((?:[^\"\\\\]|\\\\.)*)\"");
    private static final Pattern PLACEHOLDER = Pattern.compile("%(?:\\d+\\$)?[sd]");
    /** Characters a plan refusal may spend beside the item's name (M20); see the test that uses it. */
    private static final int MAX_REFUSAL_CHARS = 32;

    @Test
    void englishComesOnlyFromDatagen() {
        assertFalse(Files.exists(HAND_WRITTEN_EN_US),
                "en_us.json must not be hand-written in src/main/resources (it is generated by runData)");
        assertTrue(Files.exists(GENERATED_EN_US), "generated en_us.json missing, run ./gradlew runData");
    }

    @Test
    void germanCoversExactlyTheGeneratedKeys() throws IOException {
        Map<String, String> english = readFlatJson(GENERATED_EN_US);
        Map<String, String> german = readFlatJson(HAND_WRITTEN_DE_DE);
        assertTrue(english.containsKey("itemGroup.wareworks.base"), "generated en_us.json was not parsed: " + english);

        Set<String> missing = new TreeSet<>(english.keySet());
        missing.removeAll(german.keySet());
        Set<String> stale = new TreeSet<>(german.keySet());
        stale.removeAll(english.keySet());

        assertTrue(missing.isEmpty(), "de_de.json lacks translations for " + missing);
        assertTrue(stale.isEmpty(), "de_de.json has keys that are not generated for en_us: " + stale);
    }

    @Test
    void placeholdersMatch() throws IOException {
        Map<String, String> english = readFlatJson(GENERATED_EN_US);
        Map<String, String> german = readFlatJson(HAND_WRITTEN_DE_DE);
        english.forEach((key, value) -> {
            if (german.containsKey(key))
                assertEquals(placeholders(value), placeholders(german.get(key)), "placeholders of " + key);
        });
    }

    /**
     * Every {@link PlanRefusal} has a sentence in both languages, and every one of them <b>names the item</b> it is
     * about (M20, issue #4, ADR-032) — the promise the whole feature is judged by: a click that cannot be served says
     * which item is really missing, not that "it" is not in stock.
     * <p>
     * The length bound is the terminal's status row. It holds one line of about 216 px and the item's name has to fit
     * inside the sentence ({@code WarehouseTerminalScreen#refusedLine}), so a wordy refusal would be cut off exactly
     * before what it is about. Characters are a crude stand-in for pixels, but they catch the sentence that grew a
     * clause, which is how that row was lost before.
     */
    @Test
    void everyPlanRefusalNamesItsItemInBothLanguages() throws IOException {
        Map<String, String> english = readFlatJson(GENERATED_EN_US);
        Map<String, String> german = readFlatJson(HAND_WRITTEN_DE_DE);
        for (PlanRefusal refusal : PlanRefusal.values()) {
            String key = "wareworks." + refusal.langKey();
            for (Map.Entry<String, Map<String, String>> lang : Map.of("en_us", english, "de_de", german).entrySet()) {
                String sentence = lang.getValue().get(key);
                assertTrue(sentence != null, lang.getKey() + " has no sentence for " + key);
                assertTrue(sentence.contains("%1$s"), lang.getKey() + ": " + key + " must name the item it is about");
                assertTrue(sentence.replace("%1$s", "").length() <= MAX_REFUSAL_CHARS,
                        lang.getKey() + ": " + key + " leaves no room for the item's name in the status row: "
                                + sentence);
            }
        }
    }

    /**
     * The <b>stopped product count</b> reads the same on every surface that shows it, in every language (M20, issue #4,
     * ADR-032): a production station's goggle line, a warehouse controller's goggle line and the aisle's display board.
     * <p>
     * It is one number about one state, and a player meets it by walking from a board to a machine. English had the two
     * texts identical from the start and German did not — the board said "Angehalten: 1" and the goggles "Angehaltene
     * Produkte: 1" — which is exactly the drift this pins, because nothing else would ever notice it. Width is not a
     * reason to break it: display lines are not clipped to a board's columns ({@code WarehouseDisplays#limit}), so a
     * shorter form means a shorter form on both keys.
     */
    @Test
    void theStoppedCountReadsTheSameOnEverySurface() throws IOException {
        String goggles = "wareworks." + WareworksLangKeys.GOGGLES_PRODUCTION_STOPPED;
        String board = "wareworks." + WareworksLangKeys.DISPLAY_AISLE_LINE_STOPPED;
        for (Map.Entry<String, Path> lang : Map.of("en_us", GENERATED_EN_US, "de_de", HAND_WRITTEN_DE_DE).entrySet()) {
            Map<String, String> texts = readFlatJson(lang.getValue());
            assertEquals(texts.get(goggles), texts.get(board),
                    lang.getKey() + ": the goggle line and the display board must say the stopped count alike");
            assertTrue(texts.get(goggles) != null, lang.getKey() + " has no text for " + goggles);
        }
    }

    /**
     * The two keys of the test above, spelled out here rather than read from {@code WareworksLang}: this test suite runs
     * without Minecraft, and that class pulls in {@code Component}.
     */
    private static final class WareworksLangKeys {
        private static final String GOGGLES_PRODUCTION_STOPPED = "gui.goggles.production_stopped";
        private static final String DISPLAY_AISLE_LINE_STOPPED = "display_source.aisle.line_stopped";

        private WareworksLangKeys() {
        }
    }

    private static List<String> placeholders(String value) {
        List<String> found = new ArrayList<>();
        Matcher matcher = PLACEHOLDER.matcher(value);
        while (matcher.find())
            found.add(matcher.group());
        found.sort(String::compareTo);
        return found;
    }

    /** Minimal reader for a flat {@code {"key": "value", ...}} object; rejects duplicate keys. */
    private static Map<String, String> readFlatJson(Path path) throws IOException {
        String json = Files.readString(path, StandardCharsets.UTF_8);
        Matcher matcher = STRING.matcher(json);
        Map<String, String> entries = new LinkedHashMap<>();
        while (matcher.find()) {
            String key = unescape(matcher.group(1));
            int colon = skipWhitespace(json, matcher.end());
            if (colon >= json.length() || json.charAt(colon) != ':')
                fail(path + ": expected ':' after key " + key);
            if (!matcher.find())
                fail(path + ": missing value for key " + key);
            if (entries.put(key, unescape(matcher.group(1))) != null)
                fail(path + ": duplicate key " + key);
        }
        return entries;
    }

    private static int skipWhitespace(String text, int index) {
        int i = index;
        while (i < text.length() && Character.isWhitespace(text.charAt(i)))
            i++;
        return i;
    }

    private static String unescape(String raw) {
        StringBuilder out = new StringBuilder(raw.length());
        for (int i = 0; i < raw.length(); i++) {
            char c = raw.charAt(i);
            if (c != '\\' || i + 1 >= raw.length()) {
                out.append(c);
                continue;
            }
            char next = raw.charAt(++i);
            switch (next) {
                case 'n' -> out.append('\n');
                case 't' -> out.append('\t');
                case 'u' -> {
                    out.append((char) Integer.parseInt(raw.substring(i + 1, i + 5), 16));
                    i += 4;
                }
                default -> out.append(next);
            }
        }
        return out.toString();
    }
}
