package dev.wareworks.data;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertTrue;
import static org.junit.jupiter.api.Assertions.fail;

import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.Set;
import java.util.TreeSet;
import java.util.regex.Matcher;
import java.util.regex.Pattern;

import org.junit.jupiter.api.Test;

import dev.wareworks.core.production.PlanRefusal;

/**
 * English lang is generated by {@code runData}; German is hand-written. Every generated key must have a German
 * translation with the same format placeholders, and German must not contain stale keys.
 * <p>
 * Runs without Minecraft: it only reads the two flat JSON files. If it fails after adding lang entries, run
 * {@code ./gradlew runData} and update {@code de_de.json}.
 */
class LangConsistencyTest {
    private static final Path GENERATED_EN_US = Path.of("src/generated/resources/assets/wareworks/lang/en_us.json");
    private static final Path HAND_WRITTEN_DE_DE = Path.of("src/main/resources/assets/wareworks/lang/de_de.json");
    private static final Path HAND_WRITTEN_EN_US = Path.of("src/main/resources/assets/wareworks/lang/en_us.json");

    private static final Pattern STRING = Pattern.compile("\"((?:[^\"\\\\]|\\\\.)*)\"");
    /**
     * What counts as a placeholder for the parity check. {@code %%} is in the list since M25: it is a visible
     * character — the percent sign of {@code gui.goggles.percent} — so a translation that dropped it would show a bare
     * number, and without it here nothing would notice.
     */
    private static final Pattern PLACEHOLDER = Pattern.compile("%(?:\\d+\\$)?[sd]|%%");
    /**
     * The <b>only</b> shapes {@code TranslatableContents} accepts: {@code %%}, {@code %s} and {@code %<n>$s}
     * ({@code FORMAT_PATTERN} = {@code %(?:(\d+)\$)?([A-Za-z%]|$)}, and {@code decomposeTemplate} throws for a format
     * group whose letter is not {@code s} and for a plain segment that still holds a {@code %}).
     */
    private static final Pattern VALID_FORMAT = Pattern.compile("%(?:%|(?:\\d+\\$)?s)");
    /** Characters a plan refusal may spend beside the item's name (M20); see the test that uses it. */
    private static final int MAX_REFUSAL_CHARS = 32;
    /**
     * Blocks wide of the display board the {@code display} visual scenario builds, and the characters one of its rows
     * holds: {@code FlapDisplayBlockEntity#getMaxCharCount()} is {@code (xSize * 16 - 2) / 3.5}, and
     * {@code FlapDisplayLayout#loadDefault} gives the row one section that wide. Spelled out rather than imported,
     * because this suite runs without Minecraft.
     */
    private static final int BOARD_BLOCKS = 6;
    private static final int BOARD_CHARS = (int) ((BOARD_BLOCKS * 16f - 2f) / 3.5f);
    /**
     * Stand-in for the one argument of a throughput row, six characters wide: enough for the widest share a board can
     * show ({@code "100 %"}, German, through {@code gui.goggles.percent}) and for a five-digit grouped count
     * ({@code "99,999"}), which is far more than a crane moves in a minute.
     */
    private static final String BOARD_ARGUMENT = "123456";
    /**
     * The character budget {@code WareworksLang#aisleNamesLine} reserves for its row's label and for the mark that
     * counts the names it had no room for, and the longest name a player can give an aisle
     * ({@code AisleName#MAX_LENGTH}). Spelled out for the same reason as everything else here.
     */
    private static final int NAMES_LABEL_CHARS = 7;
    private static final int NAMES_MORE_CHARS = 6;
    private static final int NAME_CHARS = 16;

    @Test
    void englishComesOnlyFromDatagen() {
        assertFalse(Files.exists(HAND_WRITTEN_EN_US),
                "en_us.json must not be hand-written in src/main/resources (it is generated by runData)");
        assertTrue(Files.exists(GENERATED_EN_US), "generated en_us.json missing, run ./gradlew runData");
    }

    @Test
    void germanCoversExactlyTheGeneratedKeys() throws IOException {
        Map<String, String> english = readFlatJson(GENERATED_EN_US);
        Map<String, String> german = readFlatJson(HAND_WRITTEN_DE_DE);
        assertTrue(english.containsKey("itemGroup.wareworks.base"), "generated en_us.json was not parsed: " + english);

        Set<String> missing = new TreeSet<>(english.keySet());
        missing.removeAll(german.keySet());
        Set<String> stale = new TreeSet<>(german.keySet());
        stale.removeAll(english.keySet());

        assertTrue(missing.isEmpty(), "de_de.json lacks translations for " + missing);
        assertTrue(stale.isEmpty(), "de_de.json has keys that are not generated for en_us: " + stale);
    }

    @Test
    void placeholdersMatch() throws IOException {
        Map<String, String> english = readFlatJson(GENERATED_EN_US);
        Map<String, String> german = readFlatJson(HAND_WRITTEN_DE_DE);
        english.forEach((key, value) -> {
            if (german.containsKey(key))
                assertEquals(placeholders(value), placeholders(german.get(key)), "placeholders of " + key);
        });
    }

    /**
     * Every {@link PlanRefusal} has a sentence in both languages, and every one of them <b>names the item</b> it is
     * about (M20, issue #4, ADR-032) — the promise the whole feature is judged by: a click that cannot be served says
     * which item is really missing, not that "it" is not in stock.
     * <p>
     * The length bound is the terminal's status row. It holds one line of about 216 px and the item's name has to fit
     * inside the sentence ({@code WarehouseTerminalScreen#refusedLine}), so a wordy refusal would be cut off exactly
     * before what it is about. Characters are a crude stand-in for pixels, but they catch the sentence that grew a
     * clause, which is how that row was lost before.
     */
    @Test
    void everyPlanRefusalNamesItsItemInBothLanguages() throws IOException {
        Map<String, String> english = readFlatJson(GENERATED_EN_US);
        Map<String, String> german = readFlatJson(HAND_WRITTEN_DE_DE);
        for (PlanRefusal refusal : PlanRefusal.values()) {
            String key = "wareworks." + refusal.langKey();
            for (Map.Entry<String, Map<String, String>> lang : Map.of("en_us", english, "de_de", german).entrySet()) {
                String sentence = lang.getValue().get(key);
                assertTrue(sentence != null, lang.getKey() + " has no sentence for " + key);
                assertTrue(sentence.contains("%1$s"), lang.getKey() + ": " + key + " must name the item it is about");
                assertTrue(sentence.replace("%1$s", "").length() <= MAX_REFUSAL_CHARS,
                        lang.getKey() + ": " + key + " leaves no room for the item's name in the status row: "
                                + sentence);
            }
        }
    }

    /**
     * The <b>stopped product count</b> reads the same on every surface that shows it, in every language (M20, issue #4,
     * ADR-032): a production station's goggle line, a warehouse controller's goggle line and the aisle's display board.
     * <p>
     * It is one number about one state, and a player meets it by walking from a board to a machine. English had the two
     * texts identical from the start and German did not — the board said "Angehalten: 1" and the goggles "Angehaltene
     * Produkte: 1" — which is exactly the drift this pins, because nothing else would ever notice it. Width is not a
     * reason to break it: display lines are not clipped to a board's columns ({@code WarehouseDisplays#limit}), so a
     * shorter form means a shorter form on both keys.
     */
    @Test
    void theStoppedCountReadsTheSameOnEverySurface() throws IOException {
        String goggles = "wareworks." + WareworksLangKeys.GOGGLES_PRODUCTION_STOPPED;
        String board = "wareworks." + WareworksLangKeys.DISPLAY_AISLE_LINE_STOPPED;
        for (Map.Entry<String, Path> lang : Map.of("en_us", GENERATED_EN_US, "de_de", HAND_WRITTEN_DE_DE).entrySet()) {
            Map<String, String> texts = readFlatJson(lang.getValue());
            assertEquals(texts.get(goggles), texts.get(board),
                    lang.getKey() + ": the goggle line and the display board must say the stopped count alike");
            assertTrue(texts.get(goggles) != null, lang.getKey() + " has no text for " + goggles);
        }
    }

    /**
     * <b>Every percent sign in either file is one Minecraft accepts</b> (M25, issue #16, ADR-039), i.e. part of
     * {@code %%}, {@code %s} or {@code %<n>$s} and nothing else.
     * <p>
     * This is the one lang mistake that costs nothing at build time and everything at run time, and it does not even
     * crash: {@code TranslatableContents.decomposeTemplate} throws for a stray {@code %}, for a trailing one and for
     * any format letter but {@code s} — and {@code decompose()} <b>catches</b> it and falls back to
     * {@code FormattedText.of(template)}. The player is then shown the raw template, say
     * {@code "Auslastung: %1$s%% der letzten Minute"}, with nothing in any log to say why.
     * <p>
     * It guards all the keys of both files, not just the one that wants a percent sign. In particular it closes the
     * gap {@link #PLACEHOLDER} leaves open on its own: that pattern matches {@code %d}, which looks safe in a diff and
     * is fatal at run time.
     */
    @Test
    void everyPercentSignIsAFormatMinecraftAccepts() throws IOException {
        for (Map.Entry<String, Path> lang : Map.of("en_us", GENERATED_EN_US, "de_de", HAND_WRITTEN_DE_DE).entrySet()) {
            Map<String, String> texts = readFlatJson(lang.getValue());
            assertFalse(texts.isEmpty(), lang.getKey() + " was not parsed");
            texts.forEach((key, value) -> {
                Matcher matcher = VALID_FORMAT.matcher(value);
                int at = 0;
                while ((at = value.indexOf('%', at)) >= 0) {
                    assertTrue(matcher.region(at, value.length()).lookingAt(),
                            lang.getKey() + ": " + key + " has a percent sign that is neither %% nor %s at index " + at
                                    + ": " + value);
                    at = matcher.end();
                }
            });
        }
    }

    /**
     * The four rows of the Crane Throughput display source, the line that replaces them while the window is filling
     * and the one for a link without a crane all fit a display board row, <b>in both languages</b> (M25, issue #16).
     * <p>
     * A display line is never clipped to a target's columns on the server ({@code WarehouseDisplays#limit} explains
     * why), so a row that is too long is cut by the board itself and the player reads half a word. German is where
     * that happens first — {@code "Kein Regalbediengerät"} is more than twice the length of {@code "No crane"} — and
     * characters are a crude stand-in for flaps, but a board row really is monospaced, so here they are the unit.
     */
    @Test
    void theThroughputBoardRowsFitADisplayBoard() throws IOException {
        for (Map.Entry<String, Path> lang : Map.of("en_us", GENERATED_EN_US, "de_de", HAND_WRITTEN_DE_DE).entrySet()) {
            Map<String, String> texts = readFlatJson(lang.getValue());
            for (String relativeKey : WareworksLangKeys.THROUGHPUT_BOARD_KEYS) {
                String key = "wareworks." + relativeKey;
                String text = texts.get(key);
                assertTrue(text != null, lang.getKey() + " has no text for " + key);
                String filled = text.replace("%1$s", BOARD_ARGUMENT);
                assertTrue(filled.length() <= BOARD_CHARS, lang.getKey() + ": " + key + " needs " + filled.length()
                        + " of the " + BOARD_CHARS + " characters a " + BOARD_BLOCKS + "-wide board row holds: '"
                        + filled + "'");
            }
        }
    }

    /**
     * The {@code Names:} row of the Warehouse Summary source fits a display board row <b>with a name on it</b>, in
     * both languages (M25, issue #15 — review fix).
     * <p>
     * This is the other half of a bound that lives in two places. The row is built within a character budget derived
     * from the target's own width ({@code WareworksLang#aisleNamesLine}), and that budget subtracts a <b>constant</b>
     * for the label, because a display source runs on the server and may not resolve its own text there
     * ({@code WarehouseDisplays#limit} explains why). So the budget is only honest as long as no translation of this
     * label is wider than the constant — which is what this test holds both files to, for the plain row and for the
     * one that marks the names it had no room for.
     * <p>
     * Measured as the label alone, the way the production code reserves it, and then once more as a whole row filled
     * to that budget. The one case no bound can reach is a <b>single</b> name longer than the budget: the row always
     * carries at least one entry, because dropping it would leave an empty list, and cutting a player's text in half
     * is worse than letting the target do it.
     */
    @Test
    void theNamesBoardRowFitsADisplayBoard() throws IOException {
        for (Map.Entry<String, Path> lang : Map.of("en_us", GENERATED_EN_US, "de_de", HAND_WRITTEN_DE_DE).entrySet()) {
            Map<String, String> texts = readFlatJson(lang.getValue());
            for (String relativeKey : WareworksLangKeys.NAMES_BOARD_KEYS) {
                String key = "wareworks." + relativeKey;
                String text = texts.get(key);
                assertTrue(text != null, lang.getKey() + " has no text for " + key);
                boolean marksTheRest = relativeKey.endsWith("_more");
                // The label is everything but the list itself; the mark that may follow it is reserved separately.
                String label = text.replace("%1$s", "").replace("%2$s", "");
                int reserved = marksTheRest ? NAMES_LABEL_CHARS + NAMES_MORE_CHARS : NAMES_LABEL_CHARS;
                assertTrue(label.length() <= reserved, lang.getKey() + ": " + key + " keeps " + label.length()
                        + " characters for its label and mark, but WareworksLang reserves " + reserved + ": '" + label
                        + "'");
                // And a whole row filled right up to the budget that reservation leaves still fits the board. "A "
                // is the letter and its space, which every entry carries.
                int budget = BOARD_CHARS - reserved;
                String list = "A " + "X".repeat(budget - 2);
                String filled = text.replace("%1$s", list).replace("%2$s", "26");
                assertTrue(filled.length() <= BOARD_CHARS, lang.getKey() + ": " + key + " filled to its own "
                        + budget + "-character budget needs " + filled.length() + " of the " + BOARD_CHARS
                        + " characters a " + BOARD_BLOCKS + "-wide board row holds: '" + filled + "'");
            }
        }
        // The budget of the plain row really does hold the longest name a player can give, so a warehouse with one
        // named aisle is never cut on a board of this size — which is the case the feature ships for.
        assertTrue(NAMES_LABEL_CHARS + 2 + NAME_CHARS <= BOARD_CHARS, "a single longest name must fit a "
                + BOARD_BLOCKS + "-wide board row");
    }

    /**
     * The goggle rows of a package door — <b>both</b> doors, all seven — fit a goggle tooltip <b>in both
     * languages</b>, with the longest address a row can draw already in them (M26, issue #18).
     * <p>
     * A goggle line is <b>never wrapped</b>: Create's overlay passes {@code maxTextWidth = -1}, so an over-long row is
     * drawn past the edge of the box — and because the box is placed at
     * {@code min(width / 2 + offset, width - tooltipTextWidth - 20)} and then clamped to 4, one long row drags the
     * whole tooltip to the screen edge and is cut there. {@code CombVisualScenario#checkAisleListWidth} measures the
     * room one really has: the scaled screen width less 24 px, i.e. {@value #GOGGLE_ROW_PIXELS} px in the 1600x900
     * window every visual run uses (GUI scale auto is 3 there), less the {@value #GOGGLE_INDENT_PIXELS} px of indent a
     * detail row spends ({@code LangBuilder#forGoggles} writes {@code 4 + indents} spaces of 4 px).
     * <p>
     * Characters are a crude stand-in for pixels — this suite runs without Minecraft, so it has no font — but a
     * conservative {@value #GOGGLE_PIXELS_PER_CHARACTER} px per character is the advance of a plain lowercase glyph in
     * the default font, which is what these rows are made of. German is where a row runs out of room first, and the
     * row this bound is really about is the {@code LINKED} warning: at 73 characters it is the widest of the seven,
     * and the one row a player must be able to read whole, because nothing else in the game diagnoses that failure.
     * <p>
     * <b>The budget is stricter than what the mod already ships</b>, deliberately: the widest existing goggle row is
     * about 107 characters — a German {@code no_job_reason.port_full} drawn inside {@code gui.goggles.last_plan} — so
     * it was applied to these new rows only rather than retro-fitted ({@code docs/warehouse-system.md} §3.2.5).
     */
    @Test
    void thePackageDoorRowsFitAGoggleTooltip() throws IOException {
        int budget = (GOGGLE_ROW_PIXELS - GOGGLE_INDENT_PIXELS) / GOGGLE_PIXELS_PER_CHARACTER;
        for (Map.Entry<String, Path> lang : Map.of("en_us", GENERATED_EN_US, "de_de", HAND_WRITTEN_DE_DE).entrySet()) {
            Map<String, String> texts = readFlatJson(lang.getValue());
            for (String relativeKey : WareworksLangKeys.PACKAGE_DOOR_GOGGLE_KEYS) {
                String key = "wareworks." + relativeKey;
                String text = texts.get(key);
                assertTrue(text != null, lang.getKey() + " has no text for " + key);
                // The widest each row can get: the address row draws the longest address a surface shows plus the
                // mark of the cut, and every other argument of these rows is a count.
                String first = relativeKey.equals(WareworksLangKeys.PACKAGE_ADDRESS_KEY)
                        ? "W".repeat(PACKAGE_ADDRESS_CHARS) + "..." : GOGGLE_COUNT_ARGUMENT;
                String filled = text.replace("%1$s", first).replace("%2$s", GOGGLE_COUNT_ARGUMENT);
                assertTrue(filled.length() <= budget, lang.getKey() + ": " + key + " needs " + filled.length()
                        + " of the " + budget + " characters a goggle row holds: '" + filled + "'");
            }
        }
    }

    /**
     * Room a goggle tooltip has in the window every visual run uses, in scaled pixels: 1600x900 at GUI scale auto is a
     * scaled width of <b>534</b>, and Create's placement leaves 24 px of it unusable
     * ({@code CombVisualScenario#TOOLTIP_SIDE_SPACE}).
     * <p>
     * The number is the one the game itself reports rather than one computed here: {@code checkAisleListWidth} asks
     * {@code Window#getGuiScaledWidth()} and prints "the 510 px a goggle tooltip has" in every {@code comb} run, so
     * this constant and that scenario's measurement are the same number and cannot drift apart unnoticed.
     */
    private static final int GOGGLE_ROW_PIXELS = 510;
    /** Indent of a detail row: {@code forGoggles(tooltip, 2)} writes six spaces of 4 px each. */
    private static final int GOGGLE_INDENT_PIXELS = 24;
    /** Advance of a plain lowercase glyph in the default font, the conservative stand-in for measuring one. */
    private static final int GOGGLE_PIXELS_PER_CHARACTER = 6;
    /**
     * Characters of a sign address a row draws, {@code PackagerSignAddress.DISPLAY_LENGTH}. Spelled out rather than
     * imported for the reason the nested class below gives.
     */
    private static final int PACKAGE_ADDRESS_CHARS = 25;
    /**
     * Stand-in for a counted argument of a package-door row: six digits is far past what any of them can reach (the
     * stacks of a package, the free slots of a buffer, the packages one input opened since it was loaded).
     */
    private static final String GOGGLE_COUNT_ARGUMENT = "999999";

    /**
     * The keys of the tests above, spelled out here rather than read from {@code WareworksLang}: this test suite runs
     * without Minecraft, and that class pulls in {@code Component}.
     */
    private static final class WareworksLangKeys {
        private static final String GOGGLES_PRODUCTION_STOPPED = "gui.goggles.production_stopped";
        private static final String DISPLAY_AISLE_LINE_STOPPED = "display_source.aisle.line_stopped";
        /** The two forms of the Warehouse Summary source's names row (M25, issue #15). */
        private static final List<String> NAMES_BOARD_KEYS = List.of("display_source.aisle.line_names",
                "display_source.aisle.line_names_more");
        /** Every line the Crane Throughput source can put on a board (M25, issue #16). */
        private static final List<String> THROUGHPUT_BOARD_KEYS = List.of("display_source.throughput.line_trips",
                "display_source.throughput.line_items", "display_source.throughput.line_busy",
                "display_source.throughput.line_turning", "display_source.throughput.measuring",
                "display_source.throughput.no_crane");
        /** The address row, the only one of the seven below whose argument is text from the world rather than a count. */
        private static final String PACKAGE_ADDRESS_KEY = "gui.goggles.port_package_address";
        /**
         * Every goggle row a package handover adds, at <b>either</b> door (M26, issue #18): four at the out door on a
         * warehouse port, three at the in door on a warehouse input. The in door's refusal row is the only one with
         * two arguments, and it is the longest of its three.
         */
        private static final List<String> PACKAGE_DOOR_GOGGLE_KEYS = List.of("gui.goggles.port_package_handover",
                PACKAGE_ADDRESS_KEY, "gui.goggles.port_package_no_address", "gui.goggles.port_packager_linked",
                "gui.goggles.input_package_unpacking", "gui.goggles.input_packages_opened",
                "gui.goggles.input_package_refused");

        private WareworksLangKeys() {
        }
    }

    private static List<String> placeholders(String value) {
        List<String> found = new ArrayList<>();
        Matcher matcher = PLACEHOLDER.matcher(value);
        while (matcher.find())
            found.add(matcher.group());
        found.sort(String::compareTo);
        return found;
    }

    /** Minimal reader for a flat {@code {"key": "value", ...}} object; rejects duplicate keys. */
    private static Map<String, String> readFlatJson(Path path) throws IOException {
        String json = Files.readString(path, StandardCharsets.UTF_8);
        Matcher matcher = STRING.matcher(json);
        Map<String, String> entries = new LinkedHashMap<>();
        while (matcher.find()) {
            String key = unescape(matcher.group(1));
            int colon = skipWhitespace(json, matcher.end());
            if (colon >= json.length() || json.charAt(colon) != ':')
                fail(path + ": expected ':' after key " + key);
            if (!matcher.find())
                fail(path + ": missing value for key " + key);
            if (entries.put(key, unescape(matcher.group(1))) != null)
                fail(path + ": duplicate key " + key);
        }
        return entries;
    }

    private static int skipWhitespace(String text, int index) {
        int i = index;
        while (i < text.length() && Character.isWhitespace(text.charAt(i)))
            i++;
        return i;
    }

    private static String unescape(String raw) {
        StringBuilder out = new StringBuilder(raw.length());
        for (int i = 0; i < raw.length(); i++) {
            char c = raw.charAt(i);
            if (c != '\\' || i + 1 >= raw.length()) {
                out.append(c);
                continue;
            }
            char next = raw.charAt(++i);
            switch (next) {
                case 'n' -> out.append('\n');
                case 't' -> out.append('\t');
                case 'u' -> {
                    out.append((char) Integer.parseInt(raw.substring(i + 1, i + 5), 16));
                    i += 4;
                }
                default -> out.append(next);
            }
        }
        return out.toString();
    }
}
