package dev.wareworks.util;

import java.util.List;
import java.util.Locale;

import dev.wareworks.Wareworks;
import dev.wareworks.core.crane.CranePhase;
import dev.wareworks.core.inventory.InventorySummary;
import dev.wareworks.core.inventory.KeyCount;
import dev.wareworks.core.job.JobType;
import dev.wareworks.core.job.NoJobReason;
import net.createmod.catnip.lang.LangBuilder;
import net.createmod.catnip.lang.LangNumberFormat;
import net.minecraft.ChatFormatting;
import net.minecraft.network.chat.Component;
import net.minecraft.network.chat.MutableComponent;
import net.minecraft.world.item.Item;

/**
 * Runtime text helper bound to the {@code wareworks} namespace, for goggle and tooltip lines. Create's
 * {@code CreateLang} is bound to {@code create} and must not be used for our keys.
 * <p>
 * Keys passed to {@link #translate} are relative: {@code "gui.goggles.empty"} resolves to
 * {@code wareworks.gui.goggles.empty}. English values are generated by {@code dev.wareworks.data.WareworksLangGen};
 * German values live in the hand-written {@code de_de.json}. (The datagen class has a different name on purpose, so the
 * two never clash.)
 * <p>
 * Methods that add goggle lines ({@code forGoggles}) measure the client font and must only be called on the client,
 * which is where Create calls {@code addToGoggleTooltip}.
 */
public final class WareworksLang {
    /** {@code "%1$s x%2$s"}: item name and amount. */
    public static final String GOGGLES_ITEM_COUNT = "gui.goggles.item_count";
    /** {@code "Empty"}. */
    public static final String GOGGLES_EMPTY = "gui.goggles.empty";
    /** {@code "...and %1$s more"}. */
    public static final String GOGGLES_MORE_ENTRIES = "gui.goggles.more_entries";
    /** {@code "Slots: %1$s / %2$s"}. */
    public static final String GOGGLES_SLOTS_USED = "gui.goggles.slots_used";
    /** {@code "Storage Location:"}: goggle header of a warehouse interface. */
    public static final String GOGGLES_STORAGE_LOCATION = "gui.goggles.storage_location";
    /** {@code "Not part of an aisle"}: a member that stands at no rack position of a registered aisle. */
    public static final String GOGGLES_NO_AISLE = "gui.goggles.no_aisle";
    /** {@code "Address: %1$s"}: address of an aligned member, e.g. {@code A-03-07R}. */
    public static final String GOGGLES_ADDRESS = "gui.goggles.address";
    /** {@code "Misaligned"}: a member at a rack position with the wrong facing. */
    public static final String GOGGLES_MISALIGNED = "gui.goggles.misaligned";
    /** Hint under {@link #GOGGLES_MISALIGNED} for warehouse interfaces. */
    public static final String GOGGLES_MISALIGNED_HINT = "gui.goggles.misaligned_hint";
    /** {@code "Filter: %1$s"}: the store filter of a storage location. */
    public static final String GOGGLES_STORAGE_FILTER = "gui.goggles.storage_filter";
    /** {@code "Accepts everything"}: a storage location without a store filter. */
    public static final String GOGGLES_STORAGE_FILTER_NONE = "gui.goggles.storage_filter_none";
    /** Warning for a Create filter item that selects nothing, so the location would accept nothing at all. */
    public static final String GOGGLES_STORAGE_FILTER_EMPTY = "gui.goggles.storage_filter_empty";
    /** Warning for a store filter another storage location's filter shadows (shared inventory, §3.1.1). */
    public static final String GOGGLES_STORAGE_FILTER_SHADOWED = "gui.goggles.storage_filter_shadowed";
    /** {@code "Filtered locations: %1$s"}: storage locations of an aisle that carry a store filter. */
    public static final String GOGGLES_FILTERED_LOCATIONS = "gui.goggles.filtered_locations";
    /** {@code "Stored Items"}: label of the warehouse interface's store filter slot. */
    public static final String INTERFACE_STORE_FILTER = "interface.store_filter";
    /** {@code "Warehouse Controller:"}: goggle header of a warehouse controller. */
    public static final String GOGGLES_WAREHOUSE_CONTROLLER = "gui.goggles.warehouse_controller";
    /** {@code "Aisle %1$s"}: the controller's aisle letter. */
    public static final String GOGGLES_AISLE_LETTER = "gui.goggles.aisle_letter";
    /** Controller status {@code READY}. */
    public static final String GOGGLES_STATUS_READY = "gui.goggles.controller_status.ready";
    /** Controller status {@code NO_DOCK}. */
    public static final String GOGGLES_STATUS_NO_DOCK = "gui.goggles.controller_status.no_dock";
    /** Controller status {@code DOCK_MISALIGNED}: a dock stands in front, but faces another direction. */
    public static final String GOGGLES_STATUS_DOCK_MISALIGNED = "gui.goggles.controller_status.dock_misaligned";
    /** Controller status {@code NO_RAILS}. */
    public static final String GOGGLES_STATUS_NO_RAILS = "gui.goggles.controller_status.no_rails";
    /** {@code "Storage locations: %1$s"}. */
    public static final String GOGGLES_STORAGE_LOCATIONS = "gui.goggles.storage_locations";
    /** {@code "Inputs: %1$s, outputs: %2$s"}. */
    public static final String GOGGLES_STATIONS = "gui.goggles.stations";
    /** {@code "Misaligned blocks: %1$s"}. */
    public static final String GOGGLES_MISALIGNED_COUNT = "gui.goggles.misaligned_count";
    /** {@code "Item types: %1$s"}. */
    public static final String GOGGLES_ITEM_TYPES = "gui.goggles.item_types";
    /** {@code "Items stored: %1$s"}. */
    public static final String GOGGLES_ITEMS_STORED = "gui.goggles.items_stored";
    /** {@code "Aisle"}: label of the controller's value box. */
    public static final String CONTROLLER_AISLE_LETTER = "controller.aisle_letter";
    /** {@code "Letter"}: row label of the controller's hold-to-edit board. */
    public static final String CONTROLLER_AISLE_LETTER_ROW = "controller.aisle_letter_row";
    /** {@code "Inventory: %1$s"}: name of the attached inventory block. */
    public static final String GOGGLES_ATTACHED_INVENTORY = "gui.goggles.attached_inventory";
    /** {@code "No inventory attached"}. */
    public static final String GOGGLES_NO_INVENTORY = "gui.goggles.no_inventory";
    /** {@code "Stacker Crane:"}: goggle header of a stacker crane dock. */
    public static final String GOGGLES_STACKER_CRANE = "gui.goggles.stacker_crane";
    /** {@code "Aisle: %1$s long, mast %2$s high"}: aisle length and mast height. */
    public static final String GOGGLES_AISLE_SIZE = "gui.goggles.aisle_size";
    /** {@code "No controller"}. */
    public static final String GOGGLES_NO_CONTROLLER = "gui.goggles.no_controller";
    /** {@code "Controller linked"}. */
    public static final String GOGGLES_CONTROLLER_LINKED = "gui.goggles.controller_linked";
    /** {@code "Mast Height"}: label of the stacker crane's value box. */
    public static final String CRANE_MAST_HEIGHT = "crane.mast_height";
    /** Action bar text when a wrench cannot turn a busy stacker crane dock. */
    public static final String CRANE_ROTATION_LOCKED = "crane.rotation_locked";
    /** {@code "Open requests: %1$s"}: open retrieval requests of a controller. */
    public static final String GOGGLES_OPEN_REQUESTS = "gui.goggles.open_requests";
    /** {@code "Warehouse Input:"}: goggle header of a warehouse input. */
    public static final String GOGGLES_WAREHOUSE_INPUT = "gui.goggles.warehouse_input";
    /** {@code "Warehouse Output:"}: goggle header of a warehouse output. */
    public static final String GOGGLES_WAREHOUSE_OUTPUT = "gui.goggles.warehouse_output";
    /** {@code "Warehouse Terminal:"}: goggle header of a warehouse terminal. */
    public static final String GOGGLES_WAREHOUSE_TERMINAL = "gui.goggles.warehouse_terminal";
    /** {@code "Warehouse Production:"}: goggle header of a warehouse production station. */
    public static final String GOGGLES_WAREHOUSE_PRODUCTION = "gui.goggles.warehouse_production";
    /** {@code "Patterns: %1$s"}: complete patterns of a production station. */
    public static final String GOGGLES_PRODUCTION_PATTERNS = "gui.goggles.production_patterns";
    /** {@code "No patterns set"}: a production station nothing can be ordered from yet. */
    public static final String GOGGLES_PRODUCTION_NO_PATTERNS = "gui.goggles.production_no_patterns";
    /** {@code "Production orders: %1$s"}: orders running at this station. */
    public static final String GOGGLES_PRODUCTION_ORDERS = "gui.goggles.production_orders";
    /** {@code "No production order"}. */
    public static final String GOGGLES_PRODUCTION_NO_ORDERS = "gui.goggles.production_no_orders";
    /** {@code "Order: %1$s"}; the argument is a {@code ProductionOrderState} text. */
    public static final String GOGGLES_PRODUCTION_STATE = "gui.goggles.production_state";
    /** {@code "Ingredients still to fetch: %1$s"}. */
    public static final String GOGGLES_PRODUCTION_MISSING = "gui.goggles.production_missing";
    /** {@code "Waiting for results: %1$s"}. */
    public static final String GOGGLES_PRODUCTION_AWAITED = "gui.goggles.production_awaited";
    /** {@code "Production stations: %1$s"}: production stations of an aisle (controller). */
    public static final String GOGGLES_PRODUCTION_STATIONS = "gui.goggles.production_stations";
    /** Hint under {@link #GOGGLES_MISALIGNED} for stations. */
    public static final String GOGGLES_STATION_MISALIGNED_HINT = "gui.goggles.station_misaligned_hint";
    /** Hint under {@link #GOGGLES_MISALIGNED} for terminals, whose screen must not sit on the aisle side. */
    public static final String GOGGLES_TERMINAL_MISALIGNED_HINT = "gui.goggles.terminal_misaligned_hint";
    /** {@code "Buffer:"}: header of a station's buffer listing. */
    public static final String GOGGLES_BUFFER = "gui.goggles.buffer";
    /** {@code "Items requested: %1$s (requests: %2$s)"}: open requests of an output. */
    public static final String GOGGLES_PENDING_REQUESTS = "gui.goggles.pending_requests";
    /** {@code "No pending request"}. */
    public static final String GOGGLES_NO_PENDING_REQUEST = "gui.goggles.no_pending_request";
    /** {@code "Last request refused: %1$s"}; the argument is a {@code RequestRejection} text. */
    public static final String GOGGLES_LAST_REJECTION = "gui.goggles.last_rejection";
    /** {@code "Requested Item"}: label of the output's filter slot. */
    public static final String OUTPUT_REQUEST_FILTER = "output.request_filter";
    /** {@code "Requested Amount"}: title of the output's hold-to-edit amount board. */
    public static final String OUTPUT_REQUEST_AMOUNT = "output.request_amount";
    /** {@code "Status: %1$s"}: the phase of a stacker crane. */
    public static final String GOGGLES_CRANE_STATUS = "gui.goggles.crane_status";
    /** Prefix of the crane phase texts, {@code gui.goggles.crane_phase.<phase>} ({@link #cranePhaseKey}). */
    public static final String GOGGLES_CRANE_PHASE_PREFIX = "gui.goggles.crane_phase.";
    /** {@code "Paused: %1$s"}; the argument is a {@code CranePauseReason} text. */
    public static final String GOGGLES_CRANE_PAUSED = "gui.goggles.crane_paused";
    /** {@code "Storing %1$s x%2$s"}: a store job. */
    public static final String GOGGLES_CRANE_JOB_STORE = "gui.goggles.crane_job.store";
    /** {@code "Retrieving %1$s x%2$s"}: a retrieve job. */
    public static final String GOGGLES_CRANE_JOB_RETRIEVE = "gui.goggles.crane_job.retrieve";
    /** {@code "From %1$s to %2$s"}: source and target address of a job. */
    public static final String GOGGLES_CRANE_ROUTE = "gui.goggles.crane_route";
    /** {@code "Holding:"}: header of the handling head listing. */
    public static final String GOGGLES_CRANE_HOLDING = "gui.goggles.crane_holding";
    /** {@code "Grabber empty"}. */
    public static final String GOGGLES_CRANE_HEAD_EMPTY = "gui.goggles.crane_head_empty";
    /** {@code "Last planning: %1$s"}; the argument is a {@code NoJobReason} text. */
    public static final String GOGGLES_LAST_PLAN = "gui.goggles.last_plan";
    /** Prefix of the planning result texts, {@code gui.goggles.no_job_reason.<reason>} ({@link #noJobReasonKey}). */
    public static final String GOGGLES_NO_JOB_REASON_PREFIX = "gui.goggles.no_job_reason.";
    /** {@code "Delivered so far: %1$s"}: items of the open requests of an output that already arrived. */
    public static final String GOGGLES_DELIVERED_ITEMS = "gui.goggles.delivered_items";
    /** {@code "Search items"}: hint inside the terminal screen's search box. */
    public static final String TERMINAL_SEARCH = "gui.terminal.search";
    /** {@code "Sorting: %1$s"}: tooltip of the terminal screen's sort button. */
    public static final String TERMINAL_SORT = "gui.terminal.sort";
    /** Tooltip of the terminal's filter button while it hides everything that is fully promised. */
    public static final String TERMINAL_ONLY_IN_STOCK = "gui.terminal.only_in_stock";
    /** Tooltip of the terminal's filter button while it shows every item type of the aisle. */
    public static final String TERMINAL_SHOW_ALL = "gui.terminal.show_all";
    /** How a click on an item is turned into an amount (shown as a hint on the amount input and in item tooltips). */
    public static final String TERMINAL_AMOUNT_HINT = "gui.terminal.amount_hint";
    /** {@code "The aisle is empty"}: the terminal knows the stock and it is empty. */
    public static final String TERMINAL_EMPTY = "gui.terminal.empty";
    /** {@code "No item matches the search"}. */
    public static final String TERMINAL_NO_MATCH = "gui.terminal.no_match";
    /** Shown until the server's first stock payload arrives. */
    public static final String TERMINAL_LOADING = "gui.terminal.loading";
    /** {@code "Not part of an aisle"}: the terminal is misaligned, outside an aisle or has no loaded controller. */
    public static final String TERMINAL_NO_AISLE = "gui.terminal.no_aisle";
    /** {@code "Crane: %1$s"}: the crane's phase or pause reason in the terminal's status line. */
    public static final String TERMINAL_CRANE = "gui.terminal.crane";
    /** {@code "No stacker crane"}: the aisle has no loaded, linked dock. */
    public static final String TERMINAL_NO_CRANE = "gui.terminal.no_crane";
    /** {@code "Waiting for %1$s, delivered %2$s"}: this terminal's open requests. */
    public static final String TERMINAL_WAITING = "gui.terminal.waiting";
    /** {@code "Requested %1$s x%2$s"}: an accepted request. */
    public static final String TERMINAL_REQUESTED = "gui.terminal.requested";
    /**
     * {@code "Requested %1$s x%2$s, now waiting for %3$s"}: an accepted request that was merged into the terminal's open
     * request for that item ({@code docs/warehouse-system.md} §7.2), so the third number is the pending total.
     */
    public static final String TERMINAL_REQUESTED_MERGED = "gui.terminal.requested_merged";
    /** {@code "Request refused: %1$s"}; the argument is a {@code RequestRejection} text. */
    public static final String TERMINAL_REFUSED = "gui.terminal.refused";
    /** {@code "In stock: %1$s"}: item tooltip line of the terminal grid. */
    public static final String TERMINAL_STORED = "gui.terminal.stored";
    /** {@code "Available: %1$s"}: item tooltip line of the terminal grid. */
    public static final String TERMINAL_AVAILABLE = "gui.terminal.available";
    /** {@code "Promised: %1$s"}: item tooltip line of the terminal grid. */
    public static final String TERMINAL_RESERVED = "gui.terminal.reserved";
    /** {@code "Delivered here"}: label above the terminal's own buffer slots. */
    public static final String TERMINAL_BUFFER = "gui.terminal.buffer";
    /** {@code "+%1$s not shown"}: item types the aisle holds beyond {@code maxTerminalStockEntries}. */
    public static final String TERMINAL_NOT_SHOWN = "gui.terminal.not_shown";
    /** {@code "Patterns"}: label above the pattern list of a production station's screen. */
    public static final String PRODUCTION_PATTERNS = "gui.production.patterns";
    /** {@code "Delivered here"}: label above a production station's own buffer slots. */
    public static final String PRODUCTION_BUFFER = "gui.production.buffer";
    /** How a pattern cell is edited (cell tooltip). */
    public static final String PRODUCTION_HINT = "gui.production.hint";
    /** {@code "%1$s x%2$s - %3$s"}: one production order line (result, amount, state). */
    public static final String PRODUCTION_ORDER = "gui.production.order";
    /** The same line for an order that ended with ingredients already handed to the machine. */
    public static final String PRODUCTION_ORDER_LOST = "gui.production.order_lost";
    /** {@code "Ingredient"}: what a grid cell is. */
    public static final String PRODUCTION_INGREDIENT = "gui.production.ingredient";
    /** {@code "Result"}: what the result cell is. */
    public static final String PRODUCTION_RESULT = "gui.production.result";
    /** {@code "Pattern %1$s"}: the tooltip title of a pattern tab. */
    public static final String PRODUCTION_TAB = "gui.production.tab";
    /** What a click and a right-click on a pattern tab do. */
    public static final String PRODUCTION_TAB_HINT = "gui.production.tab_hint";
    /** What a click on a production order line does. */
    public static final String PRODUCTION_CANCEL_HINT = "gui.production.cancel_hint";
    /** The boundary a cancelled or timed-out order cannot undo ({@code docs/warehouse-system.md} §3.5). */
    public static final String PRODUCTION_INGREDIENTS_LOST = "gui.production.ingredients_lost";
    /** {@code "Can be produced here"}: a terminal item that is not in stock but has a pattern. */
    public static final String TERMINAL_PRODUCIBLE = "gui.terminal.producible";
    /** {@code "Can be made now: %1$s"}: how many of a producible item the ingredients in stock allow right now. */
    public static final String TERMINAL_PRODUCIBLE_AMOUNT = "gui.terminal.producible_amount";
    /** {@code "Production"}: label above the terminal's production order lines. */
    public static final String TERMINAL_PRODUCTION = "gui.terminal.production";
    /** {@code "%1$s, not recovered"}: an ended order whose delivered ingredients are gone (§3.5.4), on the line. */
    public static final String TERMINAL_ORDER_LOST = "gui.terminal.order_lost";
    /** {@code "Requested %1$s x%2$s, producing %3$s"}: an accepted request a production order was started for. */
    public static final String TERMINAL_PRODUCING = "gui.terminal.producing";
    /**
     * Name of the aisle summary display source in Create's Display Link screen. The four display source names must
     * carry exactly these keys: Create builds them as {@code <namespace>.display_source.<registry path>}
     * ({@code DisplaySource#getName}), so the path of the registry entry and the tail of the key are the same string.
     */
    public static final String DISPLAY_SOURCE_AISLE_SUMMARY = "display_source.aisle_summary";
    /** Name of the stock list display source. */
    public static final String DISPLAY_SOURCE_STOCK_LIST = "display_source.stock_list";
    /** Name of the filtered stock display source. */
    public static final String DISPLAY_SOURCE_FILTERED_STOCK = "display_source.filtered_stock";
    /** Name of the crane status display source. */
    public static final String DISPLAY_SOURCE_CRANE_STATUS = "display_source.crane_status";
    /** {@code "Aisle %1$s: %2$s"}: aisle letter and short status on a display. */
    public static final String DISPLAY_AISLE_LINE_AISLE = "display_source.aisle.line_aisle";
    /**
     * {@code "Locations: %1$s / %2$s"}: inventories of the aisle holding something, of all the aisle counts. Both
     * numbers exclude shared-inventory aliases, which never hold counts of their own
     * ({@code WarehouseControllerBlockEntity#countedStorageLocationCount()}).
     */
    public static final String DISPLAY_AISLE_LINE_LOCATIONS = "display_source.aisle.line_locations";
    /** {@code "Item types: %1$s"}. */
    public static final String DISPLAY_AISLE_LINE_ITEM_TYPES = "display_source.aisle.line_item_types";
    /** {@code "Items: %1$s"}. */
    public static final String DISPLAY_AISLE_LINE_ITEMS = "display_source.aisle.line_items";
    /** {@code "No aisle"}: the source block belongs to no loaded aisle. */
    public static final String DISPLAY_AISLE_NO_AISLE = "display_source.aisle.no_aisle";
    /**
     * Controller status {@code READY}, short. The display statuses are deliberately shorter than their goggle
     * counterparts ({@link #GOGGLES_STATUS_READY} and friends): a row of four nixie tubes shows eight characters.
     */
    public static final String DISPLAY_AISLE_STATUS_READY = "display_source.aisle.status.ready";
    /** Controller status {@code NO_DOCK}, short. */
    public static final String DISPLAY_AISLE_STATUS_NO_DOCK = "display_source.aisle.status.no_dock";
    /** Controller status {@code DOCK_MISALIGNED}, short. */
    public static final String DISPLAY_AISLE_STATUS_DOCK_MISALIGNED = "display_source.aisle.status.dock_misaligned";
    /** Controller status {@code NO_RAILS}, short. */
    public static final String DISPLAY_AISLE_STATUS_NO_RAILS = "display_source.aisle.status.no_rails";
    /** Crane activity on a display: no job. */
    public static final String DISPLAY_CRANE_IDLE = "display_source.crane.idle";
    /** Crane activity on a display: a {@code STORE} job. */
    public static final String DISPLAY_CRANE_STORING = "display_source.crane.storing";
    /** Crane activity on a display: a {@code RETRIEVE} job. */
    public static final String DISPLAY_CRANE_RETRIEVING = "display_source.crane.retrieving";
    /** Crane activity on a display: a {@code SUPPLY} job. */
    public static final String DISPLAY_CRANE_SUPPLYING = "display_source.crane.supplying";
    /** Crane activity on a display: paused, whatever the reason. */
    public static final String DISPLAY_CRANE_PAUSED = "display_source.crane.paused";
    /** {@code "%1$s x%2$s"}: the item and amount of the crane's job. */
    public static final String DISPLAY_CRANE_LINE_JOB = "display_source.crane.line_job";
    /** {@code "To %1$s"}: the address the crane is heading for. */
    public static final String DISPLAY_CRANE_LINE_TARGET = "display_source.crane.line_target";
    /** {@code "Holding %1$s"}: what the handling head carries. */
    public static final String DISPLAY_CRANE_LINE_HOLDING = "display_source.crane.line_holding";
    /** {@code "Incoming: %1$s x%2$s"}: items a crane job is bringing to a storage location. */
    public static final String GOGGLES_RESERVED_INCOMING = "gui.goggles.reserved_incoming";
    /** {@code "Reserved for pickup: %1$s x%2$s"}: items reserved inside a storage location for a crane job. */
    public static final String GOGGLES_RESERVED_OUTGOING = "gui.goggles.reserved_outgoing";

    private WareworksLang() {
    }

    /** Relative lang key of a crane phase text, e.g. {@code gui.goggles.crane_phase.travel_to_source}. */
    public static String cranePhaseKey(CranePhase phase) {
        return GOGGLES_CRANE_PHASE_PREFIX + phase.name().toLowerCase(Locale.ROOT);
    }

    /** Relative lang key of a planning result text, e.g. {@code gui.goggles.no_job_reason.warehouse_full}. */
    public static String noJobReasonKey(NoJobReason reason) {
        return GOGGLES_NO_JOB_REASON_PREFIX + reason.name().toLowerCase(Locale.ROOT);
    }

    /** "Status: phase" with the phase highlighted. */
    public static LangBuilder craneStatus(CranePhase phase) {
        return translate(GOGGLES_CRANE_STATUS, translate(cranePhaseKey(phase)).style(ChatFormatting.WHITE))
                .style(ChatFormatting.GRAY);
    }

    /** "Paused: reason" for a reason key relative to the {@code wareworks} namespace. */
    public static LangBuilder cranePaused(String reasonKey) {
        return translate(GOGGLES_CRANE_PAUSED, translate(reasonKey).style(ChatFormatting.WHITE))
                .style(ChatFormatting.GOLD);
    }

    /** "Storing item x N" / "Retrieving item x N", using the item's generic name. */
    public static LangBuilder craneJob(JobType type, Item item, long amount) {
        String key = type == JobType.STORE ? GOGGLES_CRANE_JOB_STORE : GOGGLES_CRANE_JOB_RETRIEVE;
        return translate(key, item.getDescription(), number(amount).style(ChatFormatting.GOLD))
                .style(ChatFormatting.GRAY);
    }

    /** "From A-01-00R to A-01-03L" with both addresses highlighted. */
    public static LangBuilder craneRoute(String from, String to) {
        return translate(GOGGLES_CRANE_ROUTE, text(from).style(ChatFormatting.GOLD), text(to).style(ChatFormatting.GOLD))
                .style(ChatFormatting.GRAY);
    }

    /** "Order: waiting for the result" for a production order's state. */
    public static LangBuilder productionState(dev.wareworks.core.production.ProductionOrderState state) {
        return translate(GOGGLES_PRODUCTION_STATE, translate(state.langKey()).style(ChatFormatting.WHITE))
                .style(ChatFormatting.GRAY);
    }

    /** "Last planning: reason". */
    public static LangBuilder lastPlan(NoJobReason reason) {
        return translate(GOGGLES_LAST_PLAN, translate(noJobReasonKey(reason)).style(ChatFormatting.WHITE))
                .style(ChatFormatting.GRAY);
    }

    /** Full translation key for a key relative to the {@code wareworks} namespace. */
    public static String key(String relativeKey) {
        return Wareworks.ID + "." + relativeKey;
    }

    public static LangBuilder builder() {
        return new LangBuilder(Wareworks.ID);
    }

    public static LangBuilder translate(String relativeKey, Object... args) {
        return builder().translate(relativeKey, args);
    }

    public static LangBuilder text(String literal) {
        return builder().text(literal);
    }

    /** A locale-formatted number. */
    public static LangBuilder number(double value) {
        return builder().text(LangNumberFormat.format(value));
    }

    public static MutableComponent translateDirect(String relativeKey, Object... args) {
        return Component.translatable(key(relativeKey), LangBuilder.resolveBuilders(args));
    }

    /** "item name xN" with the amount highlighted. */
    public static LangBuilder itemCount(Component itemName, long count) {
        return translate(GOGGLES_ITEM_COUNT, itemName, number(count).style(ChatFormatting.GOLD))
                .style(ChatFormatting.GRAY);
    }

    /**
     * A reservation line ({@link #GOGGLES_RESERVED_INCOMING} or {@link #GOGGLES_RESERVED_OUTGOING}): "Incoming: item xN"
     * with the amount highlighted, using the item's generic name.
     */
    public static LangBuilder reservedItems(String relativeKey, Item item, long count) {
        return translate(relativeKey, item.getDescription(), number(count).style(ChatFormatting.GOLD))
                .style(ChatFormatting.GRAY);
    }

    /** "item type name xN", using the item's generic name (never component data such as custom names). */
    public static LangBuilder itemCount(Item item, long count) {
        return itemCount(item.getDescription(), count);
    }

    /** "Aisle: L long, mast H high" with both numbers highlighted. */
    public static LangBuilder aisleSize(int length, int mastHeight) {
        return translate(GOGGLES_AISLE_SIZE, number(length).style(ChatFormatting.GOLD),
                number(mastHeight).style(ChatFormatting.GOLD)).style(ChatFormatting.GRAY);
    }

    /** "Address: A-03-07R" with the address highlighted. */
    public static LangBuilder address(String address) {
        return translate(GOGGLES_ADDRESS, text(address).style(ChatFormatting.GOLD)).style(ChatFormatting.GRAY);
    }

    /** "Aisle X" with the letter highlighted. */
    public static LangBuilder aisleLetter(char letter) {
        return translate(GOGGLES_AISLE_LETTER, text(String.valueOf(letter)).style(ChatFormatting.GOLD))
                .style(ChatFormatting.GRAY);
    }

    /** A line with one highlighted number, e.g. "Storage locations: 12", for a key with one {@code %1$s}. */
    public static LangBuilder countLine(String relativeKey, long count) {
        return translate(relativeKey, number(count).style(ChatFormatting.GOLD)).style(ChatFormatting.GRAY);
    }

    /** "Inputs: N, outputs: M". */
    public static LangBuilder stationCounts(int inputs, int outputs) {
        return translate(GOGGLES_STATIONS, number(inputs).style(ChatFormatting.GOLD),
                number(outputs).style(ChatFormatting.GOLD)).style(ChatFormatting.GRAY);
    }

    /** "Items requested: N (requests: M)" with both numbers highlighted. */
    public static LangBuilder pendingRequests(long items, int requests) {
        return translate(GOGGLES_PENDING_REQUESTS, number(items).style(ChatFormatting.GOLD),
                number(requests).style(ChatFormatting.GOLD)).style(ChatFormatting.GRAY);
    }

    /** "Last request refused: reason" for a reason key relative to the {@code wareworks} namespace. */
    public static LangBuilder lastRejection(String reasonKey) {
        return translate(GOGGLES_LAST_REJECTION, translate(reasonKey).style(ChatFormatting.WHITE))
                .style(ChatFormatting.GOLD);
    }

    /** "Slots: used / total". */
    public static LangBuilder slotsUsed(int used, int total) {
        return translate(GOGGLES_SLOTS_USED, number(used).style(ChatFormatting.GOLD), number(total))
                .style(ChatFormatting.GRAY);
    }

    /**
     * Adds a compact content listing for goggles from a (synced) summary by item type: the slot usage, then its top
     * entries and a "...and N more" line, or "Empty". Client only.
     */
    public static void addInventorySummary(List<Component> tooltip, InventorySummary<Item> summary, int indents) {
        slotsUsed(summary.usedSlots(), summary.totalSlots()).forGoggles(tooltip, indents);
        if (summary.isEmpty()) {
            translate(GOGGLES_EMPTY).style(ChatFormatting.DARK_GRAY).forGoggles(tooltip, indents + 1);
            return;
        }
        for (KeyCount<Item> entry : summary.topEntries())
            itemCount(entry.key(), entry.count()).forGoggles(tooltip, indents + 1);
        if (summary.hiddenKeys() > 0)
            translate(GOGGLES_MORE_ENTRIES, number(summary.hiddenKeys())).style(ChatFormatting.DARK_GRAY)
                    .forGoggles(tooltip, indents + 1);
    }

    /** "Filter: Iron Ingot" with the filter item's name highlighted. */
    public static LangBuilder storageFilter(Component filterName) {
        return translate(GOGGLES_STORAGE_FILTER, builder().add(filterName.copy()).style(ChatFormatting.WHITE))
                .style(ChatFormatting.GRAY);
    }

    /** "Inventory: name" with the name highlighted. */
    public static LangBuilder attachedInventory(Component blockName) {
        return translate(GOGGLES_ATTACHED_INVENTORY, builder().add(blockName.copy()).style(ChatFormatting.WHITE))
                .style(ChatFormatting.GRAY);
    }
}
