package dev.wareworks.util;

import java.util.List;
import java.util.Locale;

import dev.wareworks.Wareworks;
import dev.wareworks.core.crane.CranePhase;
import dev.wareworks.core.inventory.InventorySummary;
import dev.wareworks.core.inventory.KeyCount;
import dev.wareworks.core.job.JobType;
import dev.wareworks.core.job.NoJobReason;
import dev.wareworks.core.warehouse.LocationKind;
import dev.wareworks.core.warehouse.NetworkStop;
import net.createmod.catnip.lang.LangBuilder;
import net.createmod.catnip.lang.LangNumberFormat;
import net.minecraft.ChatFormatting;
import net.minecraft.core.BlockPos;
import net.minecraft.network.chat.Component;
import net.minecraft.network.chat.MutableComponent;
import net.minecraft.world.item.Item;

/**
 * Runtime text helper bound to the {@code wareworks} namespace, for goggle and tooltip lines. Create's
 * {@code CreateLang} is bound to {@code create} and must not be used for our keys.
 * <p>
 * Keys passed to {@link #translate} are relative: {@code "gui.goggles.empty"} resolves to
 * {@code wareworks.gui.goggles.empty}. English values are generated by {@code dev.wareworks.data.WareworksLangGen};
 * German values live in the hand-written {@code de_de.json}. (The datagen class has a different name on purpose, so the
 * two never clash.)
 * <p>
 * Methods that add goggle lines ({@code forGoggles}) measure the client font and must only be called on the client,
 * which is where Create calls {@code addToGoggleTooltip}.
 */
public final class WareworksLang {
    /**
     * What separates one aisle from the next in a list of them ({@link #networkAisles}): a spaced middle dot, which
     * needs no translation and cannot be mistaken for part of a number.
     */
    public static final String AISLE_SEPARATOR = " · ";
    /** {@code "%1$s x%2$s"}: item name and amount. */
    public static final String GOGGLES_ITEM_COUNT = "gui.goggles.item_count";
    /** {@code "Empty"}. */
    public static final String GOGGLES_EMPTY = "gui.goggles.empty";
    /** {@code "...and %1$s more"}. */
    public static final String GOGGLES_MORE_ENTRIES = "gui.goggles.more_entries";
    /** {@code "Slots: %1$s / %2$s"}. */
    public static final String GOGGLES_SLOTS_USED = "gui.goggles.slots_used";
    /** {@code "Storage Location:"}: goggle header of a warehouse interface. */
    public static final String GOGGLES_STORAGE_LOCATION = "gui.goggles.storage_location";
    /** {@code "Not part of an aisle"}: a member that stands at no rack position of a registered aisle. */
    public static final String GOGGLES_NO_AISLE = "gui.goggles.no_aisle";
    /** {@code "Address: %1$s"}: address of an aligned member, e.g. {@code A-03-07R}. */
    public static final String GOGGLES_ADDRESS = "gui.goggles.address";
    /** {@code "Misaligned"}: a member at a rack position with the wrong facing. */
    public static final String GOGGLES_MISALIGNED = "gui.goggles.misaligned";
    /**
     * {@code "The crane cannot reach this aisle"}: a member aligned at a rack position of an aisle the rails no longer
     * join to the crane (M22, issue #2). It keeps its address and its stock; nothing is planned towards it.
     */
    public static final String GOGGLES_UNREACHABLE_AISLE = "gui.goggles.unreachable_aisle";
    /** Hint under {@link #GOGGLES_MISALIGNED} for warehouse interfaces. */
    public static final String GOGGLES_MISALIGNED_HINT = "gui.goggles.misaligned_hint";
    /** {@code "Filter: %1$s"}: the store filter of a storage location. */
    public static final String GOGGLES_STORAGE_FILTER = "gui.goggles.storage_filter";
    /** {@code "Accepts everything"}: a storage location without a store filter. */
    public static final String GOGGLES_STORAGE_FILTER_NONE = "gui.goggles.storage_filter_none";
    /** Warning for a Create filter item that selects nothing, so the location would accept nothing at all. */
    public static final String GOGGLES_STORAGE_FILTER_EMPTY = "gui.goggles.storage_filter_empty";
    /** Warning for a store filter another storage location's filter shadows (shared inventory, §3.1.1). */
    public static final String GOGGLES_STORAGE_FILTER_SHADOWED = "gui.goggles.storage_filter_shadowed";
    /** {@code "Filtered locations: %1$s"}: storage locations of an aisle that carry a store filter. */
    public static final String GOGGLES_FILTERED_LOCATIONS = "gui.goggles.filtered_locations";
    /** {@code "Priority: %1$s"}: the storage priority of a storage location (M16, ADR-028). */
    public static final String GOGGLES_STORAGE_PRIORITY = "gui.goggles.storage_priority";
    /** {@code "Prioritised locations: %1$s"}: storage locations of an aisle that carry a storage priority (M16). */
    public static final String GOGGLES_PRIORITISED_LOCATIONS = "gui.goggles.prioritised_locations";
    /** {@code "Accepting ports: %1$s"}: warehouse ports of an aisle that accept items instead of requesting (M17). */
    public static final String GOGGLES_ACCEPTING_PORTS = "gui.goggles.accepting_ports";
    /** {@code "Collecting ports: %1$s"}: warehouse ports of an aisle that fetch items out of a machine (M18). */
    public static final String GOGGLES_COLLECTING_PORTS = "gui.goggles.collecting_ports";
    /** {@code "Chunk loading: %1$s chunks (%2$s)"}: an aisle that holds its chunks loaded and why (M19, issue #10). */
    public static final String GOGGLES_CHUNK_LOADING = "gui.goggles.chunk_loading";
    /** {@code "Chunk loading: none (%1$s)"}: why an aisle with work holds nothing (M19). */
    public static final String GOGGLES_CHUNK_LOADING_NONE = "gui.goggles.chunk_loading_none";
    /** {@code "Chunk loading: none (server limit: %1$s warehouses)"}: the level cap is reached (M19). */
    public static final String GOGGLES_CHUNK_LOADING_AT_LIMIT = "gui.goggles.chunk_loading_at_limit";
    /** {@code "Chunk loading: none (collecting limit: %1$s warehouses)"}: the collect opt-in's own cap is reached (M19). */
    public static final String GOGGLES_CHUNK_LOADING_AT_COLLECT_LIMIT = "gui.goggles.chunk_loading_at_collect_limit";
    /** {@code "Chunk loading: none (this warehouse needs %1$s of %2$s chunks)"}: over the per-warehouse cap (M19). */
    public static final String GOGGLES_CHUNK_LOADING_TOO_MANY = "gui.goggles.chunk_loading_too_many";
    /** Header of {@code /wareworks chunks} for one dimension. */
    public static final String COMMAND_CHUNKS_HEADER = "command.chunks.header";
    /** One holding warehouse in {@code /wareworks chunks}. */
    public static final String COMMAND_CHUNKS_ROW = "command.chunks.row";
    /** A warehouse whose reinstated hold no controller has claimed yet. */
    public static final String COMMAND_CHUNKS_ROW_UNCLAIMED = "command.chunks.row_unclaimed";
    /** One warehouse that holds nothing because its footprint is over {@code maxChunksPerAisle} (M21). */
    public static final String COMMAND_CHUNKS_ROW_OVER_CAP = "command.chunks.row_over_cap";
    /** No warehouse of the server holds anything. */
    public static final String COMMAND_CHUNKS_NONE = "command.chunks.none";
    /** Totals of {@code /wareworks chunks} over the whole server. */
    public static final String COMMAND_CHUNKS_TOTAL = "command.chunks.total";
    /** The dimension's block-ticket count (any mod) next to its whole force-loaded count. */
    public static final String COMMAND_CHUNKS_RAW = "command.chunks.raw";
    /** One warehouse was released by command. */
    public static final String COMMAND_CHUNKS_RELEASED = "command.chunks.released";
    /** Nothing was held at the given position in the dimension the command looked in. */
    public static final String COMMAND_CHUNKS_NOT_HELD = "command.chunks.not_held";
    /** Every warehouse of every dimension was released by command. */
    public static final String COMMAND_CHUNKS_RELEASED_ALL = "command.chunks.released_all";
    /** {@code "Stored Items"}: label of the warehouse interface's store filter slot. */
    public static final String INTERFACE_STORE_FILTER = "interface.store_filter";
    /** {@code "Storage Priority"}: title of the interface's hold-to-edit board (M16). */
    public static final String INTERFACE_STORE_PRIORITY = "interface.store_priority";
    /** {@code "Priority"}: the single row label of that board. */
    public static final String INTERFACE_STORE_PRIORITY_ROW = "interface.store_priority_row";
    /** Hover tip under the filter slot: hold the click to set the storage priority (M16). */
    public static final String INTERFACE_STORE_PRIORITY_TIP = "interface.store_priority_tip";
    /** {@code "Warehouse Controller:"}: goggle header of a warehouse controller. */
    public static final String GOGGLES_WAREHOUSE_CONTROLLER = "gui.goggles.warehouse_controller";
    /**
     * {@code "Warehouse %1$s"}: the letter of a whole warehouse, which is the letter of its <b>first</b> aisle — the
     * one the controller's value panel sets, and the one {@code /wareworks chunks} names a warehouse by.
     * <p>
     * Since M21 a warehouse is a set of aisles with a letter each (ADR-033), so the surfaces that speak for the
     * <b>whole</b> warehouse — the controller's goggles, the terminal's screen, the warehouse summary display — say
     * "Warehouse A" where they used to say "Aisle A". The lines that really do name one aisle still say
     * "aisle": a storage address, the dock's {@link #GOGGLES_CRANE_ON_AISLE} line and the controller's aisle list.
     */
    public static final String GOGGLES_WAREHOUSE_LETTER = "gui.goggles.warehouse_letter";
    /** Controller status {@code READY}. */
    public static final String GOGGLES_STATUS_READY = "gui.goggles.controller_status.ready";
    /** Controller status {@code NO_DOCK}. */
    public static final String GOGGLES_STATUS_NO_DOCK = "gui.goggles.controller_status.no_dock";
    /** Controller status {@code DOCK_MISALIGNED}: a dock stands in front, but faces another direction. */
    public static final String GOGGLES_STATUS_DOCK_MISALIGNED = "gui.goggles.controller_status.dock_misaligned";
    /** Controller status {@code NO_RAILS}. */
    public static final String GOGGLES_STATUS_NO_RAILS = "gui.goggles.controller_status.no_rails";
    /** {@code "Storage locations: %1$s"}. */
    public static final String GOGGLES_STORAGE_LOCATIONS = "gui.goggles.storage_locations";
    /** {@code "Inputs: %1$s, outputs: %2$s"}. */
    public static final String GOGGLES_STATIONS = "gui.goggles.stations";
    /** {@code "Misaligned blocks: %1$s"}. */
    public static final String GOGGLES_MISALIGNED_COUNT = "gui.goggles.misaligned_count";
    /** {@code "Item types: %1$s"}. */
    public static final String GOGGLES_ITEM_TYPES = "gui.goggles.item_types";
    /** {@code "Items stored: %1$s"}. */
    public static final String GOGGLES_ITEMS_STORED = "gui.goggles.items_stored";
    /** {@code "Aisle"}: label of the controller's value box. */
    public static final String CONTROLLER_AISLE_LETTER = "controller.aisle_letter";
    /** {@code "Letter"}: row label of the controller's hold-to-edit board. */
    public static final String CONTROLLER_AISLE_LETTER_ROW = "controller.aisle_letter_row";
    /** {@code "Inventory: %1$s"}: name of the attached inventory block. */
    public static final String GOGGLES_ATTACHED_INVENTORY = "gui.goggles.attached_inventory";
    /** {@code "No inventory attached"}. */
    public static final String GOGGLES_NO_INVENTORY = "gui.goggles.no_inventory";
    /** {@code "Stacker Crane:"}: goggle header of a stacker crane dock. */
    public static final String GOGGLES_STACKER_CRANE = "gui.goggles.stacker_crane";
    /** {@code "Aisle: %1$s long, mast %2$s high"}: aisle length and mast height. */
    public static final String GOGGLES_AISLE_SIZE = "gui.goggles.aisle_size";
    /**
     * {@code "Warehouse: %1$s rails, %2$s aisles, mast %3$s high"}: the size of a warehouse that bends (M21, ADR-033).
     * A warehouse of one aisle keeps showing {@link #GOGGLES_AISLE_SIZE} instead, word for word as before.
     */
    public static final String GOGGLES_NETWORK_SIZE = "gui.goggles.network_size";
    /** {@code "Aisles: %1$s"}: the letter and length of each aisle of a warehouse that bends. */
    public static final String GOGGLES_NETWORK_AISLES = "gui.goggles.network_aisles";
    /** {@code "Aisles: %1$s, and %2$s more"}: the same, for a warehouse with more aisles than a tooltip should list. */
    public static final String GOGGLES_NETWORK_AISLES_MORE = "gui.goggles.network_aisles_more";
    /** {@code "Warehouse stops at %1$s: %2$s"}: where the rails were cut off, and which reason did it. */
    public static final String GOGGLES_NETWORK_STOP = "gui.goggles.network_stop";
    /** Prefix of the one reason per {@link NetworkStop}, e.g. {@code gui.goggles.network_stop.max_junctions}. */
    public static final String GOGGLES_NETWORK_STOP_REASON = "gui.goggles.network_stop.";
    /** {@code "On aisle %1$s at position %2$s"}: where the machine of a warehouse that bends is standing. */
    public static final String GOGGLES_CRANE_ON_AISLE = "gui.goggles.crane_on_aisle";
    /** {@code "No controller"}. */
    public static final String GOGGLES_NO_CONTROLLER = "gui.goggles.no_controller";
    /** {@code "Controller linked"}. */
    public static final String GOGGLES_CONTROLLER_LINKED = "gui.goggles.controller_linked";
    /** {@code "Mast Height"}: label of the stacker crane's value box. */
    public static final String CRANE_MAST_HEIGHT = "crane.mast_height";
    /** Action bar text when a wrench cannot turn a busy stacker crane dock. */
    public static final String CRANE_ROTATION_LOCKED = "crane.rotation_locked";
    /** Action bar text after a wrench closed a warehouse rail. */
    public static final String RAIL_CLOSED = "rail.closed";
    /** Action bar text after a wrench opened a warehouse rail again. */
    public static final String RAIL_OPENED = "rail.opened";
    /** {@code "Open requests: %1$s"}: open retrieval requests of a controller. */
    public static final String GOGGLES_OPEN_REQUESTS = "gui.goggles.open_requests";
    /** {@code "Warehouse Input:"}: goggle header of a warehouse input. */
    public static final String GOGGLES_WAREHOUSE_INPUT = "gui.goggles.warehouse_input";
    /** {@code "Warehouse Output:"}: goggle header of a warehouse output. */
    public static final String GOGGLES_WAREHOUSE_OUTPUT = "gui.goggles.warehouse_output";
    /** {@code "Warehouse Terminal:"}: goggle header of a warehouse terminal. */
    public static final String GOGGLES_WAREHOUSE_TERMINAL = "gui.goggles.warehouse_terminal";
    /** {@code "Warehouse Production:"}: goggle header of a warehouse production station. */
    public static final String GOGGLES_WAREHOUSE_PRODUCTION = "gui.goggles.warehouse_production";
    /** {@code "Patterns: %1$s"}: complete patterns of a production station. */
    public static final String GOGGLES_PRODUCTION_PATTERNS = "gui.goggles.production_patterns";
    /** {@code "No patterns set"}: a production station nothing can be ordered from yet. */
    public static final String GOGGLES_PRODUCTION_NO_PATTERNS = "gui.goggles.production_no_patterns";
    /** {@code "Production orders: %1$s"}: orders running at this station. */
    public static final String GOGGLES_PRODUCTION_ORDERS = "gui.goggles.production_orders";
    /** {@code "No production order"}. */
    public static final String GOGGLES_PRODUCTION_NO_ORDERS = "gui.goggles.production_no_orders";
    /** {@code "Order: %1$s"}; the argument is a {@code ProductionOrderState} text. */
    public static final String GOGGLES_PRODUCTION_STATE = "gui.goggles.production_state";
    /** {@code "Ingredients still to fetch: %1$s"}. */
    public static final String GOGGLES_PRODUCTION_MISSING = "gui.goggles.production_missing";
    /** {@code "Waiting for results: %1$s"}. */
    public static final String GOGGLES_PRODUCTION_AWAITED = "gui.goggles.production_awaited";
    /** {@code "Production stations: %1$s"}: production stations of an aisle (controller). */
    public static final String GOGGLES_PRODUCTION_STATIONS = "gui.goggles.production_stations";
    /**
     * Chat line after a sneak-click on a production station, or a click on its screen's stopped row, lifted the safety
     * stop of one of its products (M20): {@code "The warehouse makes %1$s again"}. Used only for a stop that cost
     * nothing measurable; the ordinary case names the cost as well ({@link #PRODUCTION_RESUMED_LOST}).
     */
    public static final String PRODUCTION_RESUMED = "production.resumed";
    /**
     * The same line with what the stop cost (M20): {@code "The warehouse makes %1$s again; %2$s ingredient items were
     * delivered and never came back"}. A resume is the moment to say it — the pause is about to be gone, and with it the
     * only record of how many items were handed over without a result ({@code docs/warehouse-system.md} §3.5.4).
     * <p>
     * It says <b>delivered</b> and not "in the machine" on purpose. The number is
     * {@code ProductionOrder#deliveredIngredients()}, i.e. everything the crane dropped into the <i>station</i>, and part
     * of it may still be sitting in that station's own buffer, which a player can empty by hand. "Stayed in the machine"
     * sent a player looking inside a machine for items in the block they had just clicked, and made them write off items
     * they could pick up.
     */
    public static final String PRODUCTION_RESUMED_LOST = "production.resumed_lost";
    /** Chat line after the same click on a station none of whose products the safety stop was holding (M20). */
    public static final String PRODUCTION_NOTHING_STOPPED = "production.nothing_stopped";
    /**
     * {@code "Stopped products: %1$s"}: items the safety stop is holding — on a production station the ones it makes
     * itself, on a warehouse controller the aisle's whole count (M20, issue #4, ADR-032).
     * <p>
     * <b>One key for both</b>, and the same wording the aisle's display board uses
     * ({@link #DISPLAY_AISLE_LINE_STOPPED}): it is one number about one state, and the three surfaces that show it
     * have to be recognizable as the same thing. Until M20 the controller said "Paused after a lost batch", which was
     * written when only a stock rule's own order could arm the stop; a player now meets the same count as "stopped"
     * at the station, on the board and in the controller's tooltip. On both blocks the line outranks everything else,
     * because it is the only one that asks a player to walk to a machine.
     */
    public static final String GOGGLES_PRODUCTION_STOPPED = "gui.goggles.production_stopped";
    /**
     * How a player lets a station's products be made again (M20): on the station's goggle lines, and in its screen on the
     * tooltip of a pattern tab whose product is stopped — a tooltip that names a problem has to name the way out of it,
     * and on a station with a large buffer the tab is where a player meets the stop.
     */
    public static final String PRODUCTION_RESUME_HINT = "production.resume_hint";
    /**
     * {@code "Stopped: %1$s. Click to make it again"}: the row a production station's screen shows instead of its first
     * order line while the safety stop holds exactly one of its products (M20).
     */
    public static final String PRODUCTION_STOPPED_LINE = "gui.production.stopped_line";
    /** The same row for a station with several stopped products: {@code "Stopped: %1$s products. ..."} (M20). */
    public static final String PRODUCTION_STOPPED_LINE_MANY = "gui.production.stopped_line_many";
    /** {@code "%1$s: %2$s"}: one stopped product of that row's tooltip, the item first and then why it stopped (M20). */
    public static final String PRODUCTION_STOPPED_ITEM = "gui.production.stopped_item";
    /** {@code "Stock rules: %1$s"}: rules of the aisle's stock keepers that govern an item (controller, M15). */
    public static final String GOGGLES_STOCK_RULES = "gui.goggles.stock_rules";
    /** {@code "Below minimum: %1$s"}: governing rules of the aisle whose item the warehouse is short of. */
    public static final String GOGGLES_RULES_BELOW_MINIMUM = "gui.goggles.rules_below_minimum";
    /** {@code "At maximum: %1$s"}: governing rules of the aisle that stop their item from being stored. */
    public static final String GOGGLES_RULES_AT_MAXIMUM = "gui.goggles.rules_at_maximum";

    /**
     * {@code "Warehouse Home Point:"}: goggle header of a warehouse home point (M21, ADR-034). The sentence below it
     * is the one of its {@code HomePointStatus}, whose own {@code langKey()} names it.
     */
    public static final String GOGGLES_WAREHOUSE_HOME_POINT = "gui.goggles.warehouse_home_point";

    /** {@code "Warehouse Stock Keeper:"}: goggle header of a warehouse stock keeper (M15). */
    public static final String GOGGLES_WAREHOUSE_STOCK_KEEPER = "gui.goggles.warehouse_stock_keeper";
    /** {@code "Rules: %1$s"}: rows of a keeper that hold a rule. */
    public static final String GOGGLES_KEEPER_RULES = "gui.goggles.keeper_rules";
    /** {@code "No rules set"}: a keeper that governs nothing yet. */
    public static final String GOGGLES_KEEPER_NO_RULES = "gui.goggles.keeper_no_rules";
    /** {@code "Not part of a warehouse"}: a keeper no loaded controller reads. */
    public static final String GOGGLES_KEEPER_NO_WAREHOUSE = "gui.goggles.keeper_no_warehouse";
    /** {@code "Below minimum: %1$s"}: governing rules whose item the warehouse is short of. */
    public static final String GOGGLES_KEEPER_BELOW_MINIMUM = "gui.goggles.keeper_below_minimum";
    /** {@code "At maximum: %1$s"}: governing rules whose item is not accepted any more. */
    public static final String GOGGLES_KEEPER_AT_MAXIMUM = "gui.goggles.keeper_at_maximum";
    /** {@code "Down to the reserve: %1$s"}: governing rules that hold the rest back from automation. */
    public static final String GOGGLES_KEEPER_AT_RESERVE = "gui.goggles.keeper_at_reserve";
    /** {@code "Being made now: %1$s"}: rules the warehouse is restocking by itself (M15 part 2). */
    public static final String GOGGLES_KEEPER_ORDERING = "gui.goggles.keeper_ordering";
    /** {@code "Waiting for ingredients: %1$s"}: rules that are short and cannot order (M15 part 2). */
    public static final String GOGGLES_KEEPER_WAITING = "gui.goggles.keeper_waiting";
    /** {@code "Paused after a lost batch: %1$s"}: rules the safety stop is holding (M15 part 2). */
    public static final String GOGGLES_KEEPER_PAUSED = "gui.goggles.keeper_paused";
    /** The one-line "what to do about it" under {@link #GOGGLES_KEEPER_PAUSED}. */
    public static final String GOGGLES_KEEPER_PAUSED_HINT = "gui.goggles.keeper_paused_hint";
    /** {@code "Without effect: %1$s"}: rules shadowed by an earlier one or beyond the aisle's rule limit. */
    public static final String GOGGLES_KEEPER_WITHOUT_EFFECT = "gui.goggles.keeper_without_effect";
    /** {@code "Everything within its limits"}: no rule of this keeper bites. */
    public static final String GOGGLES_KEEPER_SATISFIED = "gui.goggles.keeper_satisfied";
    /** {@code "Rules"}: label above the rule rows of a keeper's screen. */
    public static final String KEEPER_RULES = "gui.keeper.rules";
    /** {@code "Empty row"}: a rule row without an item. */
    public static final String KEEPER_EMPTY_ROW = "gui.keeper.empty_row";
    /** {@code "Minimum"}: tooltip title of the first number column. */
    public static final String KEEPER_MINIMUM = "gui.keeper.minimum";
    /** {@code "Maximum"}: tooltip title of the second number column. */
    public static final String KEEPER_MAXIMUM = "gui.keeper.maximum";
    /** {@code "Reserve"}: tooltip title of the third number column. */
    public static final String KEEPER_RESERVE = "gui.keeper.reserve";
    /** {@code "Min"}: column header of the minimum. */
    public static final String KEEPER_MINIMUM_SHORT = "gui.keeper.minimum_short";
    /** {@code "Max"}: column header of the maximum. */
    public static final String KEEPER_MAXIMUM_SHORT = "gui.keeper.maximum_short";
    /** {@code "Res"}: column header of the reserve. */
    public static final String KEEPER_RESERVE_SHORT = "gui.keeper.reserve_short";
    /** What the minimum governs: what comes in. */
    public static final String KEEPER_MINIMUM_HINT = "gui.keeper.minimum_hint";
    /** What the maximum governs: what may be stored. */
    public static final String KEEPER_MAXIMUM_HINT = "gui.keeper.maximum_hint";
    /** What the reserve governs: what may go out to the warehouse's own automation. */
    public static final String KEEPER_RESERVE_HINT = "gui.keeper.reserve_hint";
    /** How a number is changed (number tooltip). */
    public static final String KEEPER_NUMBER_HINT = "gui.keeper.number_hint";
    /** How a rule's item is set (item cell tooltip). */
    public static final String KEEPER_ITEM_HINT = "gui.keeper.item_hint";
    /** The status line of the keeper screen while nothing had to be corrected. */
    public static final String KEEPER_HINT = "gui.keeper.hint";
    /** The status line while no controller reads these rules. */
    public static final String KEEPER_NO_WAREHOUSE = "gui.keeper.no_warehouse";
    /** {@code "Min %1$s \u00b7 Max %2$s \u00b7 Reserve %3$s"}: the exact numbers of a rule, also when a field is compacted. */
    public static final String KEEPER_LIMITS = "gui.keeper.limits";
    /** {@code "In stock: %1$s"}: what the aisle holds of a rule's item. */
    public static final String KEEPER_IN_STOCK = "gui.keeper.in_stock";
    /** {@code "Available: %1$s"}: what a player could still ask for at a terminal. */
    public static final String KEEPER_AVAILABLE = "gui.keeper.available";
    /** {@code "Held back from automation: %1$s"}: what the reserve keeps from redstone requests. */
    public static final String KEEPER_HELD_BACK = "gui.keeper.held_back";
    /** {@code "Short of the minimum: %1$s"}. */
    public static final String KEEPER_SHORTFALL = "gui.keeper.shortfall";
    /** Prefix of the rule status texts, {@code gui.keeper.status.<status>} ({@link #keeperStatusKey}). */
    public static final String KEEPER_STATUS_PREFIX = "gui.keeper.status.";
    /** Prefix of the correction texts, {@code gui.keeper.adjustment.<adjustment>} ({@link #keeperAdjustmentKey}). */
    public static final String KEEPER_ADJUSTMENT_PREFIX = "gui.keeper.adjustment.";
    /** Prefix of the restocking texts, {@code gui.keeper.restock.<outcome>} ({@code RestockOutcome#langKey}). */
    public static final String KEEPER_RESTOCK_PREFIX = "gui.keeper.restock.";
    /** {@code "Ingredient items delivered and never returned: %1$s"}: what a paused rule's lost batch cost (M15 part 2); the count is what the crane delivered to the station, not what the machine swallowed. */
    public static final String KEEPER_PAUSED_LOST = "gui.keeper.paused_lost";
    /** How a player lets a paused rule order again (row tooltip and status line, M15 part 2). */
    public static final String KEEPER_RESUME_HINT = "gui.keeper.resume_hint";
    /** The status line while the safety stop is holding a rule of this keeper (M15 part 2). */
    public static final String KEEPER_PAUSED_LINE = "gui.keeper.paused_line";
    /** {@code "Missing: %1$s"}: the ingredient a waiting rule needs a player to supply (M15 part 2). */
    public static final String KEEPER_MISSING_INGREDIENT = "gui.keeper.missing_ingredient";
    /** The status line after an edit lifted a rule's safety stop (M15 part 2). */
    public static final String KEEPER_RESUMED = "gui.keeper.resumed";
    /** Hint under {@link #GOGGLES_MISALIGNED} for stations. */
    public static final String GOGGLES_STATION_MISALIGNED_HINT = "gui.goggles.station_misaligned_hint";
    /** Hint under {@link #GOGGLES_MISALIGNED} for terminals, whose screen must not sit on the aisle side. */
    public static final String GOGGLES_TERMINAL_MISALIGNED_HINT = "gui.goggles.terminal_misaligned_hint";
    /** {@code "Buffer:"}: header of a station's buffer listing. */
    public static final String GOGGLES_BUFFER = "gui.goggles.buffer";
    /** {@code "Items requested: %1$s (requests: %2$s)"}: open requests of an output. */
    public static final String GOGGLES_PENDING_REQUESTS = "gui.goggles.pending_requests";
    /** {@code "No pending request"}. */
    public static final String GOGGLES_NO_PENDING_REQUEST = "gui.goggles.no_pending_request";
    /** {@code "Last request refused: %1$s"}; the argument is a {@code RequestRejection} text. */
    public static final String GOGGLES_LAST_REJECTION = "gui.goggles.last_rejection";
    /** {@code "Requested Item"}: label of the output's filter slot. */
    public static final String OUTPUT_REQUEST_FILTER = "output.request_filter";
    /** {@code "Requested Amount"}: title of the output's hold-to-edit amount board. */
    public static final String OUTPUT_REQUEST_AMOUNT = "output.request_amount";
    /**
     * {@code "Accepted Item"}: label of the same filter slot in the {@code ACCEPT} direction, where the filter says
     * which items the port takes at all rather than which one to fetch (M17, issue #12).
     */
    public static final String OUTPUT_ACCEPT_FILTER = "output.accept_filter";
    /**
     * {@code "Collected Item"}: label of the same filter slot in the {@code COLLECT} direction, where the filter says
     * which items the port fetches out of the machine behind it (M18, issue #13).
     */
    public static final String OUTPUT_COLLECT_FILTER = "output.collect_filter";
    /**
     * {@code "Port"}: title of the same board in the accepting direction, where the amount is not a setting and only
     * the rows — the redstone behaviour — mean anything (M17).
     */
    public static final String OUTPUT_PORT_BOARD = "output.port_board";
    /** {@code "Port Direction"}: label and board title of the port's wrench-only direction and rank box (M17). */
    public static final String OUTPUT_PORT_RANK = "output.port_rank";
    /** Hover tip under the filter slot of an <b>accepting</b> port: hold the click to set when the port acts (M17). */
    public static final String OUTPUT_PORT_REDSTONE_TIP = "output.port_redstone_tip";
    /**
     * The same hover tip on a <b>requesting</b> port, where the board's column is the requested amount as well (M17):
     * Create's own "Hold to set amount" would leave the rows unsaid, and this key's counterpart would leave the amount
     * unsaid.
     */
    public static final String OUTPUT_REQUEST_AMOUNT_TIP = "output.request_amount_tip";
    /** {@code "Redstone: %1$s"}: when a port acts, with a {@code PortRedstone} text (M17). */
    public static final String GOGGLES_PORT_REDSTONE = "gui.goggles.port_redstone";
    /** {@code "Active"}: a continuous port whose redstone gate is open right now (M17). */
    public static final String GOGGLES_PORT_ACTIVE = "gui.goggles.port_active";
    /** {@code "Waiting for a signal"}: a continuous port whose redstone gate is closed (M17). */
    public static final String GOGGLES_PORT_WAITING = "gui.goggles.port_waiting";
    /** {@code "Port: overflow (%1$s)"}: an accepting port that ranks after storage; the argument is the signed rank. */
    public static final String GOGGLES_PORT_OVERFLOW = "gui.goggles.port_overflow";
    /** {@code "Port: diversion (%1$s)"}: an accepting port that ranks before storage; the argument is the signed rank. */
    public static final String GOGGLES_PORT_DIVERSION = "gui.goggles.port_diversion";
    /** {@code "Accepts: %1$s"}: which items an accepting port handles at all (M17). */
    public static final String GOGGLES_PORT_ACCEPTS = "gui.goggles.port_accepts";
    /** {@code "Any item"}: an accepting port without a filter (M17). */
    public static final String GOGGLES_PORT_ACCEPTS_ANY = "gui.goggles.port_accepts_any";
    /** {@code "Handed over: %1$s"}: items an accepting port has exported since it was built (M17). */
    public static final String GOGGLES_PORT_EXPORTED = "gui.goggles.port_exported";
    /** {@code "Port: collects into the warehouse"}: the direction line of a collecting port (M18, issue #13). */
    public static final String GOGGLES_PORT_COLLECTING = "gui.goggles.port_collecting";
    /** {@code "Collects: %1$s"}: which items a collecting port fetches at all (M18). */
    public static final String GOGGLES_PORT_COLLECTS = "gui.goggles.port_collects";
    /** {@code "Ready: %1$s"}: items the port's last read of the inventory behind it found (M18). */
    public static final String GOGGLES_PORT_COLLECT_READY = "gui.goggles.port_collect_ready";
    /** {@code "Collected: %1$s"}: items a collecting port has fetched into the warehouse since it was built (M18). */
    public static final String GOGGLES_PORT_COLLECTED = "gui.goggles.port_collected";
    /** {@code "No inventory behind the port"}: a collecting port with nothing to fetch from (M18). */
    public static final String GOGGLES_PORT_NO_INVENTORY = "gui.goggles.port_no_inventory";
    /**
     * {@code "This inventory is already a storage location"}: a collecting port pointed at an inventory its own aisle
     * counts, which is refused, because collecting from it would be an endless crane shuffle (M18, issue #13).
     */
    public static final String GOGGLES_PORT_COLLECT_OWN_STORAGE = "gui.goggles.port_collect_own_storage";
    /**
     * {@code "Not fetched: %1$s"}: why the warehouse did not take what waits behind a collecting port — the aisle's
     * planning reason, on the block a player is pointing at (M18 review). The argument is a {@code NoJobReason} text.
     */
    public static final String GOGGLES_PORT_COLLECT_REFUSED = "gui.goggles.port_collect_refused";
    /** {@code "Status: %1$s"}: the phase of a stacker crane. */
    public static final String GOGGLES_CRANE_STATUS = "gui.goggles.crane_status";
    /** Prefix of the crane phase texts, {@code gui.goggles.crane_phase.<phase>} ({@link #cranePhaseKey}). */
    public static final String GOGGLES_CRANE_PHASE_PREFIX = "gui.goggles.crane_phase.";
    /** {@code "Paused: %1$s"}; the argument is a {@code CranePauseReason} text. */
    public static final String GOGGLES_CRANE_PAUSED = "gui.goggles.crane_paused";
    /** {@code "Storing %1$s x%2$s"}: a store job. */
    public static final String GOGGLES_CRANE_JOB_STORE = "gui.goggles.crane_job.store";
    /** {@code "Retrieving %1$s x%2$s"}: a retrieve job. */
    public static final String GOGGLES_CRANE_JOB_RETRIEVE = "gui.goggles.crane_job.retrieve";
    /**
     * {@code "Handing over %1$s x%2$s"}: a store job whose target is an accepting warehouse port, i.e. items the
     * warehouse hands out instead of storing (M17, issue #12).
     */
    public static final String GOGGLES_CRANE_JOB_HAND_OVER = "gui.goggles.crane_job.hand_over";
    /**
     * {@code "Collecting %1$s x%2$s"}: a collect job, i.e. items the crane is fetching out of the inventory behind a
     * collecting warehouse port (M18, issue #13).
     */
    public static final String GOGGLES_CRANE_JOB_COLLECT = "gui.goggles.crane_job.collect";
    /** {@code "From %1$s to %2$s"}: source and target address of a job. */
    public static final String GOGGLES_CRANE_ROUTE = "gui.goggles.crane_route";
    /** {@code "Holding:"}: header of the handling head listing. */
    public static final String GOGGLES_CRANE_HOLDING = "gui.goggles.crane_holding";
    /** {@code "Grabber empty"}. */
    public static final String GOGGLES_CRANE_HEAD_EMPTY = "gui.goggles.crane_head_empty";
    /** {@code "Last planning: %1$s"}; the argument is a {@code NoJobReason} text. */
    public static final String GOGGLES_LAST_PLAN = "gui.goggles.last_plan";
    /** Prefix of the planning result texts, {@code gui.goggles.no_job_reason.<reason>} ({@link #noJobReasonKey}). */
    public static final String GOGGLES_NO_JOB_REASON_PREFIX = "gui.goggles.no_job_reason.";
    /** {@code "Delivered so far: %1$s"}: items of the open requests of an output that already arrived. */
    public static final String GOGGLES_DELIVERED_ITEMS = "gui.goggles.delivered_items";
    /** {@code "Search items"}: hint inside the terminal screen's search box. */
    public static final String TERMINAL_SEARCH = "gui.terminal.search";
    /** {@code "Sorting: %1$s"}: tooltip of the terminal screen's sort button. */
    public static final String TERMINAL_SORT = "gui.terminal.sort";
    /** Tooltip of the terminal's filter button while it hides everything that is fully promised. */
    public static final String TERMINAL_ONLY_IN_STOCK = "gui.terminal.only_in_stock";
    /** Tooltip of the terminal's filter button while it shows every item type of the aisle. */
    public static final String TERMINAL_SHOW_ALL = "gui.terminal.show_all";
    /** How a click on an item is turned into an amount (shown as a hint on the amount input and in item tooltips). */
    public static final String TERMINAL_AMOUNT_HINT = "gui.terminal.amount_hint";
    /** {@code "The aisle is empty"}: the terminal knows the stock and it is empty. */
    public static final String TERMINAL_EMPTY = "gui.terminal.empty";
    /** {@code "No item matches the search"}. */
    public static final String TERMINAL_NO_MATCH = "gui.terminal.no_match";
    /** Shown until the server's first stock payload arrives. */
    public static final String TERMINAL_LOADING = "gui.terminal.loading";
    /**
     * {@code "Not part of a warehouse"}: the terminal is misaligned, outside a warehouse or has no loaded
     * controller. It is drawn in the very slot that otherwise reads {@link #GOGGLES_WAREHOUSE_LETTER}
     * "Warehouse A", so it speaks of the warehouse as that line does (M22 review fix); the key keeps its path,
     * because only the text changed.
     */
    public static final String TERMINAL_NO_AISLE = "gui.terminal.no_aisle";
    /** {@code "Crane: %1$s"}: the crane's phase or pause reason in the terminal's status line. */
    public static final String TERMINAL_CRANE = "gui.terminal.crane";
    /** {@code "No stacker crane"}: the aisle has no loaded, linked dock. */
    public static final String TERMINAL_NO_CRANE = "gui.terminal.no_crane";
    /** {@code "Waiting for %1$s, delivered %2$s"}: this terminal's open requests. */
    public static final String TERMINAL_WAITING = "gui.terminal.waiting";
    /** {@code "Requested %1$s x%2$s"}: an accepted request. */
    public static final String TERMINAL_REQUESTED = "gui.terminal.requested";
    /**
     * {@code "Requested %1$s x%2$s, now waiting for %3$s"}: an accepted request that was merged into the terminal's open
     * request for that item ({@code docs/warehouse-system.md} §7.2), so the third number is the pending total.
     */
    public static final String TERMINAL_REQUESTED_MERGED = "gui.terminal.requested_merged";
    /** {@code "Request refused: %1$s"}; the argument is a {@code RequestRejection} text. */
    public static final String TERMINAL_REFUSED = "gui.terminal.refused";
    /** {@code "In stock: %1$s"}: item tooltip line of the terminal grid. */
    public static final String TERMINAL_STORED = "gui.terminal.stored";
    /** {@code "Available: %1$s"}: item tooltip line of the terminal grid. */
    public static final String TERMINAL_AVAILABLE = "gui.terminal.available";
    /** {@code "Promised: %1$s"}: item tooltip line of the terminal grid. */
    public static final String TERMINAL_RESERVED = "gui.terminal.reserved";
    /** {@code "Stock rule: %1$s"}: what a rule says about this item, with a {@code StockRuleStatus} text (M15). */
    public static final String TERMINAL_RULE = "gui.terminal.rule";
    /** {@code "Kept back from automation: %1$s"}: the reserve, which this player may still take. */
    public static final String TERMINAL_RULE_RESERVED = "gui.terminal.rule_reserved";
    /** {@code "Stored at most: %1$s"}: the rule's storage cap, the third of its numbers a row can name (M15 part 2). */
    public static final String TERMINAL_RULE_MAXIMUM = "gui.terminal.rule_maximum";
    /** {@code "A request of yours goes below the reserve"}: the hint that tells a player which case they are in. */
    public static final String TERMINAL_BELOW_RESERVE = "gui.terminal.below_reserve";
    /** Title of the terminal's confirmation panel (M15 part 2). */
    public static final String TERMINAL_CONFIRM_TITLE = "gui.terminal.confirm.title";
    /** {@code "This takes %1$s of the %2$s items held in reserve."}: the reserve case (M15 part 2). */
    public static final String TERMINAL_CONFIRM_RESERVE = "gui.terminal.confirm.reserve";
    /** {@code "%1$s of these %2$s go past the maximum of %3$s."}: the maximum case (M15 part 2). */
    public static final String TERMINAL_CONFIRM_MAXIMUM = "gui.terminal.confirm.maximum";
    /**
     * {@code "Making it takes %1$s of the %2$s reserved %3$s."}: an ingredient of the production order the request
     * would start, held back by a reserve of its own (M15 part 2). Only the server can name this, because only it has
     * the aisle's patterns.
     */
    public static final String TERMINAL_CONFIRM_INGREDIENT = "gui.terminal.confirm.ingredient";
    /** {@code "The warehouse has changed since you were asked:"}: the re-check found a higher cost (M15 part 2). */
    public static final String TERMINAL_CONFIRM_CHANGED = "gui.terminal.confirm.changed";
    /** {@code "Confirm"}: the button that carries the request out. */
    public static final String TERMINAL_CONFIRM_YES = "gui.terminal.confirm.yes";
    /** {@code "Cancel"}: the button that drops it. */
    public static final String TERMINAL_CONFIRM_NO = "gui.terminal.confirm.no";
    /** How to skip the confirmation next time (Ctrl), shown under the two buttons. */
    public static final String TERMINAL_CONFIRM_SKIP = "gui.terminal.confirm.skip";
    /** {@code "Delivered here"}: label above the terminal's own buffer slots. */
    public static final String TERMINAL_BUFFER = "gui.terminal.buffer";
    /** {@code "+%1$s not shown"}: item types the aisle holds beyond {@code maxTerminalStockEntries}. */
    public static final String TERMINAL_NOT_SHOWN = "gui.terminal.not_shown";
    /** {@code "Patterns"}: label above the pattern list of a production station's screen. */
    public static final String PRODUCTION_PATTERNS = "gui.production.patterns";
    /** {@code "Delivered here"}: label above a production station's own buffer slots. */
    public static final String PRODUCTION_BUFFER = "gui.production.buffer";
    /** How a pattern cell is edited (cell tooltip). */
    public static final String PRODUCTION_HINT = "gui.production.hint";
    /** {@code "%1$s x%2$s - %3$s"}: one production order line (result, amount, state). */
    public static final String PRODUCTION_ORDER = "gui.production.order";
    /** The same line for an order that ended with ingredients already handed to the machine. */
    public static final String PRODUCTION_ORDER_LOST = "gui.production.order_lost";
    /** {@code "Ingredient"}: what a grid cell is. */
    public static final String PRODUCTION_INGREDIENT = "gui.production.ingredient";
    /** {@code "Result"}: what the result cell is. */
    public static final String PRODUCTION_RESULT = "gui.production.result";
    /** {@code "Pattern %1$s"}: the tooltip title of a pattern tab. */
    public static final String PRODUCTION_TAB = "gui.production.tab";
    /** What a click and a right-click on a pattern tab do. */
    public static final String PRODUCTION_TAB_HINT = "gui.production.tab_hint";
    /** What a click on a production order line does. */
    public static final String PRODUCTION_CANCEL_HINT = "gui.production.cancel_hint";
    /** The boundary a cancelled or timed-out order cannot undo ({@code docs/warehouse-system.md} §3.5). */
    public static final String PRODUCTION_INGREDIENTS_LOST = "gui.production.ingredients_lost";
    /**
     * {@code "waiting for an earlier step"}: where an order of a chain stands while another order of its own plan is
     * still making one of its ingredients (M20, issue #4, ADR-032).
     * <p>
     * It stands beside the {@code ProductionOrderState} sentences without being one of them: such an order <i>is</i> in
     * {@code WAITING_FOR_INGREDIENTS}, but it is fetching nothing at all until the step below it is done, and a surface
     * that said "waiting for ingredients" would look like a stuck crane. One key for one sentence, because all three
     * surfaces that can show it — the terminal's step panel, a production station's own order rows and that station's
     * goggle line — have to say the same thing about the same order.
     */
    public static final String PRODUCTION_WAITING_FOR_STEP = "gui.production.waiting_for_step";
    /** {@code "Can be produced here"}: a terminal item that is not in stock but has a pattern. */
    public static final String TERMINAL_PRODUCIBLE = "gui.terminal.producible";
    /** {@code "Can be made now: %1$s"}: how many of a producible item the ingredients in stock allow right now. */
    public static final String TERMINAL_PRODUCIBLE_AMOUNT = "gui.terminal.producible_amount";
    /** {@code "Production"}: label above the terminal's production order lines. */
    public static final String TERMINAL_PRODUCTION = "gui.terminal.production";
    /** {@code "%1$s, not recovered"}: an ended order whose delivered ingredients are gone (§3.5.4), on the line. */
    public static final String TERMINAL_ORDER_LOST = "gui.terminal.order_lost";
    /** {@code "Requested %1$s x%2$s, producing %3$s"}: an accepted request a production order was started for. */
    public static final String TERMINAL_PRODUCING = "gui.terminal.producing";

    // --- a production plan in the terminal (M20, issue #4, ADR-032) -------------------------------------------------
    /**
     * {@code "now: %1$s"}: the right-hand half of a chain's line in the terminal's production section. What it holds is
     * the state of the <b>frontier</b> — the step where something is really happening — because the ordered item's own
     * state ("waiting for ingredients") is the one thing a player already knows.
     */
    public static final String TERMINAL_PLAN_FRONTIER = "gui.terminal.plan.frontier";
    /**
     * {@code "%1$s steps"}: the badge on a chain's line that opens the step panel, counting <b>every</b> order of the
     * chain. A badge is only ever drawn for a chain of at least two orders, so the plural is always right.
     */
    public static final String TERMINAL_PLAN_STEPS = "gui.terminal.plan.steps";
    /** {@code "Chain for %1$s x%2$s"}: the title of the step panel. */
    public static final String TERMINAL_PLAN_TITLE = "gui.terminal.plan.title";
    /** {@code "%1$s: %2$s"}: one step of the panel, the address of its station first so the rows read as a list. */
    public static final String TERMINAL_PLAN_STEP_AT = "gui.terminal.plan.step_at";
    /** What a step whose station the aisle cannot name is prefixed with instead of an address. */
    public static final String TERMINAL_PLAN_NO_ADDRESS = "gui.terminal.plan.no_address";
    /**
     * {@code "Steps that would end: %1$s"}: the first of the three things giving up on a chain costs. The number is the
     * one the server would really end ({@code core.terminal.PlanCancelCost}), not how many steps are open — a step whose
     * batch is already in a machine is left running on purpose.
     */
    public static final String TERMINAL_PLAN_CANCEL_COST = "gui.terminal.plan.cancel_cost";
    /**
     * The second: ingredient items the warehouse already delivered to a station and will never fetch back ({@code
     * §3.5.4}). It says <b>delivered</b> rather than "in the machine", because part of it may still be sitting in the
     * station's own buffer where a player can take it out by hand — the number is what the crane handed over, and a
     * message that sends a player looking inside their machine for items one block away is worse than no number.
     */
    public static final String TERMINAL_PLAN_CANCEL_LOST = "gui.terminal.plan.cancel_lost";
    /**
     * The third, and the one a player cannot see coming: giving up on a chain whose step already had ingredients
     * <b>arms the safety stop</b> for that item, so the warehouse makes none of it until somebody resumes it at the
     * machine (ADR-027 widened by ADR-032). Shown under exactly the same condition as
     * {@link #TERMINAL_PLAN_CANCEL_LOST}, because that is the condition the server arms it under.
     */
    public static final String TERMINAL_PLAN_CANCEL_STOP = "gui.terminal.plan.cancel_stop";
    /** {@code "Give up on the chain"}: the panel's own button, which cancels every step of it. */
    public static final String TERMINAL_PLAN_CANCEL = "gui.terminal.plan.cancel";
    /** {@code "Close"}: the panel's other button. */
    public static final String TERMINAL_PLAN_CLOSE = "gui.terminal.plan.close";
    /** What a click on a chain's line does, on its tooltip. */
    public static final String TERMINAL_PLAN_HINT = "gui.terminal.plan.hint";
    /** What the {@code x} at the end of a chain's line does, on its tooltip. */
    public static final String TERMINAL_PLAN_CANCEL_HINT = "gui.terminal.plan.cancel_hint";
    /**
     * Name of the aisle summary display source in Create's Display Link screen. The four display source names must
     * carry exactly these keys: Create builds them as {@code <namespace>.display_source.<registry path>}
     * ({@code DisplaySource#getName}), so the path of the registry entry and the tail of the key are the same string.
     */
    public static final String DISPLAY_SOURCE_AISLE_SUMMARY = "display_source.aisle_summary";
    /** Name of the stock list display source. */
    public static final String DISPLAY_SOURCE_STOCK_LIST = "display_source.stock_list";
    /** Name of the filtered stock display source. */
    public static final String DISPLAY_SOURCE_FILTERED_STOCK = "display_source.filtered_stock";
    /** Name of the crane status display source. */
    public static final String DISPLAY_SOURCE_CRANE_STATUS = "display_source.crane_status";
    /** {@code "Aisle %1$s: %2$s"}: aisle letter and short status on a display. */
    public static final String DISPLAY_AISLE_LINE_AISLE = "display_source.aisle.line_aisle";
    /**
     * {@code "Locations: %1$s / %2$s"}: inventories of the aisle holding something, of all the aisle counts. Both
     * numbers exclude shared-inventory aliases, which never hold counts of their own
     * ({@code WarehouseControllerBlockEntity#countedStorageLocationCount()}).
     */
    public static final String DISPLAY_AISLE_LINE_LOCATIONS = "display_source.aisle.line_locations";
    /** {@code "Item types: %1$s"}. */
    public static final String DISPLAY_AISLE_LINE_ITEM_TYPES = "display_source.aisle.line_item_types";
    /** {@code "Items: %1$s"}. */
    public static final String DISPLAY_AISLE_LINE_ITEMS = "display_source.aisle.line_items";
    /**
     * {@code "Rules: %1$s · below min %2$s · at max %3$s"}: the aisle's governing stock rules, how many call for their
     * item and how many refuse it at their maximum (M15). The last number is the one that explains a warehouse input
     * standing still, so a board that watches the aisle has to be able to show it; the wording follows the goggle lines
     * ({@link #GOGGLES_RULES_BELOW_MINIMUM}, {@link #GOGGLES_RULES_AT_MAXIMUM}), shortened for a display row.
     */
    public static final String DISPLAY_AISLE_LINE_RULES = "display_source.aisle.line_rules";
    /**
     * {@code "Stopped products: %1$s"}: items of the aisle the safety stop is holding (M15 part 2, reworded in M20).
     * <p>
     * It counted <b>rules</b> and said so until M20: since a lost batch of <i>any</i> order arms the stop (issue #4,
     * ADR-032), the item it holds is regularly an intermediate of a chain that no stock rule governs at all — an aisle
     * without a single stock keeper can be showing this line. The wording follows the production station's own goggle
     * line ({@link #GOGGLES_PRODUCTION_STOPPED}), because that station is where a player goes to lift it — and that has
     * to hold in <b>every</b> language, so {@code LangConsistencyTest} makes the two texts identical in each of them.
     * Shortening one of the two for a narrow display board means shortening both.
     */
    public static final String DISPLAY_AISLE_LINE_STOPPED = "display_source.aisle.line_stopped";
    /**
     * {@code "Ports: %1$s accepting"}: warehouse ports of the aisle that accept items instead of requesting them
     * (M17, issue #12). Left out entirely while none does, exactly like the two stock rule lines.
     */
    public static final String DISPLAY_AISLE_LINE_PORTS = "display_source.aisle.line_ports";
    /**
     * {@code "Ports: %1$s accepting, %2$s collecting"}: the same line when the aisle has both kinds of port (M18, issue
     * #13). Two keys rather than one with an optional half, because a lang file cannot leave an argument out: each half is
     * shown only while it is above 0, so a four-tube board never loses a number to a zero.
     */
    public static final String DISPLAY_AISLE_LINE_PORTS_BOTH = "display_source.aisle.line_ports_both";
    /** {@code "Ports: %1$s collecting"}: an aisle with collecting ports and no accepting one (M18). */
    public static final String DISPLAY_AISLE_LINE_PORTS_COLLECTING = "display_source.aisle.line_ports_collecting";
    /** {@code "Chunks: %1$s held"}: the aisle is holding its own chunks loaded (M19, issue #10). */
    public static final String DISPLAY_AISLE_LINE_CHUNKS = "display_source.aisle.line_chunks";
    /** {@code "Aisles: %1$s"}: the letters of a warehouse that bends (M21, issue #1). */
    public static final String DISPLAY_AISLE_LINE_AISLES = "display_source.aisle.line_aisles";
    /**
     * {@code "Aisles: %1$s (cut short)"}: the same, while the discovery stopped short of what the player laid. The
     * reason takes a sentence, which is why the board only marks it and the controller's goggles name it.
     */
    public static final String DISPLAY_AISLE_LINE_AISLES_CUT = "display_source.aisle.line_aisles_cut";
    /**
     * {@code "No warehouse"}: the source block belongs to no loaded warehouse, and this is then the whole output
     * of the Warehouse Summary source — which is why it speaks of a warehouse like every other line of it
     * (M22 review fix). The key keeps its path, because only the text changed.
     */
    public static final String DISPLAY_AISLE_NO_AISLE = "display_source.aisle.no_aisle";
    /**
     * Controller status {@code READY}, short. The display statuses are deliberately shorter than their goggle
     * counterparts ({@link #GOGGLES_STATUS_READY} and friends): a row of four nixie tubes shows eight characters.
     */
    public static final String DISPLAY_AISLE_STATUS_READY = "display_source.aisle.status.ready";
    /** Controller status {@code NO_DOCK}, short. */
    public static final String DISPLAY_AISLE_STATUS_NO_DOCK = "display_source.aisle.status.no_dock";
    /** Controller status {@code DOCK_MISALIGNED}, short. */
    public static final String DISPLAY_AISLE_STATUS_DOCK_MISALIGNED = "display_source.aisle.status.dock_misaligned";
    /** Controller status {@code NO_RAILS}, short. */
    public static final String DISPLAY_AISLE_STATUS_NO_RAILS = "display_source.aisle.status.no_rails";
    /** Crane activity on a display: no job. */
    public static final String DISPLAY_CRANE_IDLE = "display_source.crane.idle";
    /** Crane activity on a display: a {@code STORE} job. */
    public static final String DISPLAY_CRANE_STORING = "display_source.crane.storing";
    /** Crane activity on a display: a {@code RETRIEVE} job. */
    public static final String DISPLAY_CRANE_RETRIEVING = "display_source.crane.retrieving";
    /** Crane activity on a display: a {@code SUPPLY} job. */
    public static final String DISPLAY_CRANE_SUPPLYING = "display_source.crane.supplying";
    /**
     * Crane activity on a display: the items are on their way to an accepting warehouse port, i.e. out of the warehouse
     * (M17, issue #12). A store job that is really an export must not read as "Storing".
     */
    public static final String DISPLAY_CRANE_HANDING_OVER = "display_source.crane.handing_over";
    /**
     * Crane activity on a display: the items are on their way <b>out of a machine</b> into the racks, i.e. a
     * {@code COLLECT} job (M18, issue #13). A collect must not read as "Storing": what a player wants to see is that the
     * warehouse is fetching.
     */
    public static final String DISPLAY_CRANE_COLLECTING = "display_source.crane.collecting";
    /** Crane activity on a display: paused, whatever the reason. */
    public static final String DISPLAY_CRANE_PAUSED = "display_source.crane.paused";
    /** {@code "%1$s x%2$s"}: the item and amount of the crane's job. */
    public static final String DISPLAY_CRANE_LINE_JOB = "display_source.crane.line_job";
    /** {@code "To %1$s"}: the address the crane is heading for. */
    public static final String DISPLAY_CRANE_LINE_TARGET = "display_source.crane.line_target";
    /** {@code "Holding %1$s"}: what the handling head carries. */
    public static final String DISPLAY_CRANE_LINE_HOLDING = "display_source.crane.line_holding";
    /** {@code "Incoming: %1$s x%2$s"}: items a crane job is bringing to a storage location. */
    public static final String GOGGLES_RESERVED_INCOMING = "gui.goggles.reserved_incoming";
    /** {@code "Reserved for pickup: %1$s x%2$s"}: items reserved inside a storage location for a crane job. */
    public static final String GOGGLES_RESERVED_OUTGOING = "gui.goggles.reserved_outgoing";

    private WareworksLang() {
    }

    /** Relative lang key of a crane phase text, e.g. {@code gui.goggles.crane_phase.travel_to_source}. */
    public static String cranePhaseKey(CranePhase phase) {
        return GOGGLES_CRANE_PHASE_PREFIX + phase.name().toLowerCase(Locale.ROOT);
    }

    /** Relative lang key of a stock rule status, e.g. {@code gui.keeper.status.below_minimum}. */
    public static String keeperStatusKey(dev.wareworks.core.stock.StockRuleStatus status) {
        return KEEPER_STATUS_PREFIX + status.name().toLowerCase(Locale.ROOT);
    }

    /** Relative lang key of a correction a rule edit needed, e.g. {@code gui.keeper.adjustment.value_clamped}. */
    public static String keeperAdjustmentKey(dev.wareworks.core.stock.StockRuleAdjustment adjustment) {
        return KEEPER_ADJUSTMENT_PREFIX + adjustment.name().toLowerCase(Locale.ROOT);
    }

    /** Relative lang key of a restocking outcome, e.g. {@code gui.keeper.restock.waiting_for_ingredients}. */
    public static String keeperRestockKey(dev.wareworks.core.stock.RestockOutcome outcome) {
        return outcome.langKey();
    }

    /** Relative lang key of why a rule was paused, e.g. {@code gui.keeper.paused.timed_out}. */
    public static String keeperPausedKey(dev.wareworks.core.stock.StockRulePause.Cause cause) {
        return cause.langKey();
    }

    /** Relative lang key of a planning result text, e.g. {@code gui.goggles.no_job_reason.warehouse_full}. */
    public static String noJobReasonKey(NoJobReason reason) {
        return GOGGLES_NO_JOB_REASON_PREFIX + reason.name().toLowerCase(Locale.ROOT);
    }

    /** Relative lang key of a discovery stop reason, e.g. {@code gui.goggles.network_stop.max_junctions}. */
    public static String networkStopKey(NetworkStop stop) {
        return GOGGLES_NETWORK_STOP_REASON + stop.name().toLowerCase(Locale.ROOT);
    }

    /** "Status: phase" with the phase highlighted. */
    public static LangBuilder craneStatus(CranePhase phase) {
        return translate(GOGGLES_CRANE_STATUS, translate(cranePhaseKey(phase)).style(ChatFormatting.WHITE))
                .style(ChatFormatting.GRAY);
    }

    /** "Paused: reason" for a reason key relative to the {@code wareworks} namespace. */
    public static LangBuilder cranePaused(String reasonKey) {
        return translate(GOGGLES_CRANE_PAUSED, translate(reasonKey).style(ChatFormatting.WHITE))
                .style(ChatFormatting.GOLD);
    }

    /**
     * "Storing item x N" / "Retrieving item x N" / "Handing over item x N" / "Collecting item x N", using the item's
     * generic name.
     * <p>
     * The third case is a store job into an accepting warehouse port (M17, issue #12): the type alone would call it
     * "Storing" although the items are leaving the warehouse, so the target's kind decides. The fourth is a collect job
     * (M18, issue #13), which is the opposite direction and has a name of its own.
     */
    public static LangBuilder craneJob(JobType type, LocationKind targetKind, Item item, long amount) {
        String key = switch (type) {
            case COLLECT -> GOGGLES_CRANE_JOB_COLLECT;
            case STORE -> targetKind == LocationKind.OUTPUT ? GOGGLES_CRANE_JOB_HAND_OVER : GOGGLES_CRANE_JOB_STORE;
            case RETRIEVE, SUPPLY -> GOGGLES_CRANE_JOB_RETRIEVE;
        };
        return translate(key, item.getDescription(), number(amount).style(ChatFormatting.GOLD))
                .style(ChatFormatting.GRAY);
    }

    /** "From A-01-00R to A-01-03L" with both addresses highlighted. */
    public static LangBuilder craneRoute(String from, String to) {
        return translate(GOGGLES_CRANE_ROUTE, text(from).style(ChatFormatting.GOLD), text(to).style(ChatFormatting.GOLD))
                .style(ChatFormatting.GRAY);
    }

    /** "Order: waiting for the result" for a production order's state. */
    public static LangBuilder productionState(dev.wareworks.core.production.ProductionOrderState state) {
        return translate(GOGGLES_PRODUCTION_STATE, translate(state.langKey()).style(ChatFormatting.WHITE))
                .style(ChatFormatting.GRAY);
    }

    /**
     * "Order: waiting for an earlier step" — the same line for a chain step the aisle is deliberately handing nothing
     * while an earlier step of its own plan is still running (M20, issue #4, ADR-032).
     */
    public static LangBuilder productionWaitingForStep() {
        return translate(GOGGLES_PRODUCTION_STATE, translate(PRODUCTION_WAITING_FOR_STEP).style(ChatFormatting.WHITE))
                .style(ChatFormatting.GRAY);
    }

    /** "Chunk loading: 6 chunks (crane job)" for an aisle that is holding its chunks (M19, issue #10). */
    public static LangBuilder chunkLoading(int chunks, dev.wareworks.content.controller.ChunkKeepReason reason) {
        return translate(GOGGLES_CHUNK_LOADING, number(chunks).style(ChatFormatting.GOLD),
                translate(reason.langKey()).style(ChatFormatting.WHITE)).style(ChatFormatting.GRAY);
    }

    /** "Chunk loading: none (let go; holds again when its work changes)" for an aisle that holds nothing (M19). */
    public static LangBuilder chunkLoadingNone(dev.wareworks.content.controller.ChunkKeepReason reason) {
        return translate(GOGGLES_CHUNK_LOADING_NONE, translate(reason.langKey()).style(ChatFormatting.WHITE))
                .style(ChatFormatting.GOLD);
    }

    /** "Chunk loading: none (server limit: 4 warehouses)" (M19, M21). */
    public static LangBuilder chunkLoadingAtLimit(int maxAisles) {
        return translate(GOGGLES_CHUNK_LOADING_AT_LIMIT, number(maxAisles).style(ChatFormatting.WHITE))
                .style(ChatFormatting.GOLD);
    }

    /** "Chunk loading: none (collecting limit: 1 warehouses)" (M19, M21). */
    public static LangBuilder chunkLoadingAtCollectLimit(int maxAisles) {
        return translate(GOGGLES_CHUNK_LOADING_AT_COLLECT_LIMIT, number(maxAisles).style(ChatFormatting.WHITE))
                .style(ChatFormatting.GOLD);
    }

    /** "Chunk loading: none (this warehouse needs 12 of 10 chunks)" (M19, M21). */
    public static LangBuilder chunkLoadingTooMany(int needed, int allowed) {
        return translate(GOGGLES_CHUNK_LOADING_TOO_MANY, number(needed).style(ChatFormatting.WHITE),
                number(allowed).style(ChatFormatting.WHITE)).style(ChatFormatting.GOLD);
    }

    /** "Last planning: reason". */
    public static LangBuilder lastPlan(NoJobReason reason) {
        return translate(GOGGLES_LAST_PLAN, translate(noJobReasonKey(reason)).style(ChatFormatting.WHITE))
                .style(ChatFormatting.GRAY);
    }

    /** Full translation key for a key relative to the {@code wareworks} namespace. */
    public static String key(String relativeKey) {
        return Wareworks.ID + "." + relativeKey;
    }

    public static LangBuilder builder() {
        return new LangBuilder(Wareworks.ID);
    }

    public static LangBuilder translate(String relativeKey, Object... args) {
        return builder().translate(relativeKey, args);
    }

    public static LangBuilder text(String literal) {
        return builder().text(literal);
    }

    /** A locale-formatted number. */
    public static LangBuilder number(double value) {
        return builder().text(LangNumberFormat.format(value));
    }

    public static MutableComponent translateDirect(String relativeKey, Object... args) {
        return Component.translatable(key(relativeKey), LangBuilder.resolveBuilders(args));
    }

    /** "item name xN" with the amount highlighted. */
    public static LangBuilder itemCount(Component itemName, long count) {
        return translate(GOGGLES_ITEM_COUNT, itemName, number(count).style(ChatFormatting.GOLD))
                .style(ChatFormatting.GRAY);
    }

    /**
     * A reservation line ({@link #GOGGLES_RESERVED_INCOMING} or {@link #GOGGLES_RESERVED_OUTGOING}): "Incoming: item xN"
     * with the amount highlighted, using the item's generic name.
     */
    public static LangBuilder reservedItems(String relativeKey, Item item, long count) {
        return translate(relativeKey, item.getDescription(), number(count).style(ChatFormatting.GOLD))
                .style(ChatFormatting.GRAY);
    }

    /** "item type name xN", using the item's generic name (never component data such as custom names). */
    public static LangBuilder itemCount(Item item, long count) {
        return itemCount(item.getDescription(), count);
    }

    /** "Aisle: L long, mast H high" with both numbers highlighted. */
    public static LangBuilder aisleSize(int length, int mastHeight) {
        return translate(GOGGLES_AISLE_SIZE, number(length).style(ChatFormatting.GOLD),
                number(mastHeight).style(ChatFormatting.GOLD)).style(ChatFormatting.GRAY);
    }

    /** "Warehouse: N rails, M aisles, mast H high" with every number highlighted (M21, ADR-033). */
    public static LangBuilder networkSize(int rails, int aisles, int mastHeight) {
        return translate(GOGGLES_NETWORK_SIZE, number(rails).style(ChatFormatting.GOLD),
                number(aisles).style(ChatFormatting.GOLD), number(mastHeight).style(ChatFormatting.GOLD))
                .style(ChatFormatting.GRAY);
    }

    /**
     * "Aisles: A 16 · B 12 · C 13", or "Aisles: A 16 · B 12, and 4 more" once the list is longer than {@code listed}.
     * <p>
     * The list itself is built rather than translated: it is aisle letters and rail counts, which read the same in
     * every language, and one key per possible aisle count would be unmaintainable. The separator is the middle dot
     * every Wareworks surface already uses between two numbers of one line.
     *
     * @param entries one "letter length" entry per aisle, in aisle order
     * @param listed  how many of them the line may name
     */
    public static LangBuilder networkAisles(List<String> entries, int listed) {
        int shown = Math.min(entries.size(), Math.max(1, listed));
        String list = String.join(AISLE_SEPARATOR, entries.subList(0, shown));
        if (shown == entries.size())
            return translate(GOGGLES_NETWORK_AISLES, text(list).style(ChatFormatting.GOLD))
                    .style(ChatFormatting.GRAY);
        return translate(GOGGLES_NETWORK_AISLES_MORE, text(list).style(ChatFormatting.GOLD),
                number(entries.size() - shown).style(ChatFormatting.GOLD)).style(ChatFormatting.GRAY);
    }

    /** "Warehouse stops at x y z: &lt;reason&gt;", the line that says where a player has to go and look. */
    public static LangBuilder networkStop(BlockPos stopped, NetworkStop stop) {
        return translate(GOGGLES_NETWORK_STOP,
                text(stopped.getX() + " " + stopped.getY() + " " + stopped.getZ()).style(ChatFormatting.GOLD),
                translate(networkStopKey(stop)).style(ChatFormatting.GOLD))
                .style(ChatFormatting.GRAY);
    }

    /** "On aisle B at position 7" with both highlighted: where the machine is standing on a warehouse that bends. */
    public static LangBuilder craneOnAisle(char letter, int position) {
        return translate(GOGGLES_CRANE_ON_AISLE, text(String.valueOf(letter)).style(ChatFormatting.GOLD),
                number(position).style(ChatFormatting.GOLD)).style(ChatFormatting.GRAY);
    }

    /** "Address: A-03-07R" with the address highlighted. */
    public static LangBuilder address(String address) {
        return translate(GOGGLES_ADDRESS, text(address).style(ChatFormatting.GOLD)).style(ChatFormatting.GRAY);
    }

    /** "Warehouse X" with the letter highlighted ({@link #GOGGLES_WAREHOUSE_LETTER}). */
    public static LangBuilder warehouseLetter(char letter) {
        return translate(GOGGLES_WAREHOUSE_LETTER, text(String.valueOf(letter)).style(ChatFormatting.GOLD))
                .style(ChatFormatting.GRAY);
    }

    /** A line with one highlighted number, e.g. "Storage locations: 12", for a key with one {@code %1$s}. */
    public static LangBuilder countLine(String relativeKey, long count) {
        return translate(relativeKey, number(count).style(ChatFormatting.GOLD)).style(ChatFormatting.GRAY);
    }

    /** "Inputs: N, outputs: M". */
    public static LangBuilder stationCounts(int inputs, int outputs) {
        return translate(GOGGLES_STATIONS, number(inputs).style(ChatFormatting.GOLD),
                number(outputs).style(ChatFormatting.GOLD)).style(ChatFormatting.GRAY);
    }

    /** "Items requested: N (requests: M)" with both numbers highlighted. */
    public static LangBuilder pendingRequests(long items, int requests) {
        return translate(GOGGLES_PENDING_REQUESTS, number(items).style(ChatFormatting.GOLD),
                number(requests).style(ChatFormatting.GOLD)).style(ChatFormatting.GRAY);
    }

    /** "Last request refused: reason" for a reason key relative to the {@code wareworks} namespace. */
    public static LangBuilder lastRejection(String reasonKey) {
        return translate(GOGGLES_LAST_REJECTION, translate(reasonKey).style(ChatFormatting.WHITE))
                .style(ChatFormatting.GOLD);
    }

    /** "Slots: used / total". */
    public static LangBuilder slotsUsed(int used, int total) {
        return translate(GOGGLES_SLOTS_USED, number(used).style(ChatFormatting.GOLD), number(total))
                .style(ChatFormatting.GRAY);
    }

    /**
     * Adds a compact content listing for goggles from a (synced) summary by item type: the slot usage, then its top
     * entries and a "...and N more" line, or "Empty". Client only.
     */
    public static void addInventorySummary(List<Component> tooltip, InventorySummary<Item> summary, int indents) {
        slotsUsed(summary.usedSlots(), summary.totalSlots()).forGoggles(tooltip, indents);
        if (summary.isEmpty()) {
            translate(GOGGLES_EMPTY).style(ChatFormatting.DARK_GRAY).forGoggles(tooltip, indents + 1);
            return;
        }
        for (KeyCount<Item> entry : summary.topEntries())
            itemCount(entry.key(), entry.count()).forGoggles(tooltip, indents + 1);
        if (summary.hiddenKeys() > 0)
            translate(GOGGLES_MORE_ENTRIES, number(summary.hiddenKeys())).style(ChatFormatting.DARK_GRAY)
                    .forGoggles(tooltip, indents + 1);
    }

    /** "Filter: Iron Ingot" with the filter item's name highlighted. */
    public static LangBuilder storageFilter(Component filterName) {
        return translate(GOGGLES_STORAGE_FILTER, builder().add(filterName.copy()).style(ChatFormatting.WHITE))
                .style(ChatFormatting.GRAY);
    }

    /** "Inventory: name" with the name highlighted. */
    public static LangBuilder attachedInventory(Component blockName) {
        return translate(GOGGLES_ATTACHED_INVENTORY, builder().add(blockName.copy()).style(ChatFormatting.WHITE))
                .style(ChatFormatting.GRAY);
    }
}
