package dev.wareworks.client.ponder;

import com.simibubi.create.infrastructure.ponder.AllCreatePonderTags;
import com.tterrag.registrate.util.entry.ItemProviderEntry;
import com.tterrag.registrate.util.entry.RegistryEntry;

import dev.wareworks.client.ponder.scenes.CraneScenes;
import dev.wareworks.client.ponder.scenes.PortScenes;
import dev.wareworks.client.ponder.scenes.ProductionScenes;
import dev.wareworks.client.ponder.scenes.StockRuleScenes;
import dev.wareworks.client.ponder.scenes.TerminalScenes;
import dev.wareworks.client.ponder.scenes.WarehouseScenes;
import dev.wareworks.registry.WareworksBlocks;
import net.createmod.ponder.api.registration.PonderSceneRegistrationHelper;
import net.minecraft.resources.ResourceLocation;

/**
 * Which scene is shown for which item.
 * <p>
 * The component of a storyboard is the <b>item id</b>: it decides whose tooltip says "Hold [W] to Ponder" and what
 * {@code /ponder <id>} opens. Every Wareworks block therefore appears as a component of at least one scene, and blocks
 * that take part in several stories get several (scene order per component is registration order).
 * <p>
 * The tags passed to {@code addStoryBoard} only make those tags flash in the UI; membership is in
 * {@link WareworksPonderTags}.
 * <p>
 * Schematic paths resolve to {@code assets/wareworks/ponder/<path>.nbt} and are generated by
 * {@code scripts/gen_ponder_schematics.py}. Scene ids (the first argument of {@code scene.title}) must be unique
 * within the {@code wareworks} namespace, because they are the lang key prefix of the scene's texts.
 * <p>
 * The scene count per component is asserted by the {@code ponder} visual scenario
 * ({@code dev.wareworks.dev.PonderVisualScenario}), so a lost registration fails that run.
 *
 * <table>
 *   <caption>Scenes per component</caption>
 *   <tr><th>Component</th><th>Scenes</th></tr>
 *   <tr><td>stacker_crane, warehouse_rail</td><td>stacker_crane/overview</td></tr>
 *   <tr><td>warehouse_interface</td><td>warehouse/interface, warehouse/filters, warehouse/storing</td></tr>
 *   <tr><td>warehouse_controller</td><td>warehouse/storing, warehouse/retrieving</td></tr>
 *   <tr><td>warehouse_input</td><td>warehouse/storing</td></tr>
 *   <tr><td>warehouse_output</td><td>warehouse/retrieving, warehouse/port_requesting, warehouse/port_accepting,
 *       warehouse/port_collecting</td></tr>
 *   <tr><td>warehouse_terminal</td><td>warehouse/terminal, warehouse/requesting</td></tr>
 *   <tr><td>warehouse_production</td><td>warehouse/production, warehouse/port_collecting</td></tr>
 *   <tr><td>warehouse_stock_keeper</td><td>warehouse/stock_rules, warehouse/restocking,
 *       warehouse/port_accepting</td></tr>
 * </table>
 */
public final class WareworksPonderScenes {
    private WareworksPonderScenes() {
    }

    public static void register(PonderSceneRegistrationHelper<ResourceLocation> helper) {
        PonderSceneRegistrationHelper<ItemProviderEntry<?, ?>> scenes = helper.withKeyFunction(RegistryEntry::getId);

        scenes.forComponents(WareworksBlocks.STACKER_CRANE, WareworksBlocks.WAREHOUSE_RAIL)
                .addStoryBoard("stacker_crane/overview", CraneScenes::overview,
                        WareworksPonderTags.WAREHOUSE, AllCreatePonderTags.KINETIC_APPLIANCES);

        scenes.forComponents(WareworksBlocks.WAREHOUSE_INTERFACE)
                .addStoryBoard("warehouse/interface", WarehouseScenes::warehouseInterface,
                        WareworksPonderTags.WAREHOUSE);

        scenes.forComponents(WareworksBlocks.WAREHOUSE_INTERFACE)
                .addStoryBoard("warehouse/filters", WarehouseScenes::storageFilters,
                        WareworksPonderTags.WAREHOUSE);

        scenes.forComponents(WareworksBlocks.WAREHOUSE_INPUT, WareworksBlocks.WAREHOUSE_CONTROLLER,
                        WareworksBlocks.WAREHOUSE_INTERFACE)
                .addStoryBoard("warehouse/storing", WarehouseScenes::storing,
                        WareworksPonderTags.WAREHOUSE, AllCreatePonderTags.LOGISTICS);

        scenes.forComponents(WareworksBlocks.WAREHOUSE_OUTPUT, WareworksBlocks.WAREHOUSE_CONTROLLER)
                .addStoryBoard("warehouse/retrieving", WarehouseScenes::retrieving,
                        WareworksPonderTags.WAREHOUSE, AllCreatePonderTags.LOGISTICS);

        scenes.forComponents(WareworksBlocks.WAREHOUSE_TERMINAL)
                .addStoryBoard("warehouse/terminal", TerminalScenes::placing,
                        WareworksPonderTags.WAREHOUSE);

        scenes.forComponents(WareworksBlocks.WAREHOUSE_TERMINAL)
                .addStoryBoard("warehouse/requesting", TerminalScenes::requesting,
                        WareworksPonderTags.WAREHOUSE, AllCreatePonderTags.LOGISTICS);

        scenes.forComponents(WareworksBlocks.WAREHOUSE_PRODUCTION)
                .addStoryBoard("warehouse/production", ProductionScenes::production,
                        WareworksPonderTags.WAREHOUSE, AllCreatePonderTags.LOGISTICS);

        scenes.forComponents(WareworksBlocks.WAREHOUSE_STOCK_KEEPER)
                .addStoryBoard("warehouse/stock_rules", StockRuleScenes::stockRules,
                        WareworksPonderTags.WAREHOUSE, AllCreatePonderTags.LOGISTICS);

        scenes.forComponents(WareworksBlocks.WAREHOUSE_STOCK_KEEPER)
                .addStoryBoard("warehouse/restocking", StockRuleScenes::restocking,
                        WareworksPonderTags.WAREHOUSE, AllCreatePonderTags.LOGISTICS);

        // The two port scenes come last on purpose (M17, issue #12): scene order per component is registration order,
        // so registering them here leaves warehouse/retrieving the first thing a warehouse output shows and
        // warehouse/stock_rules the first thing a stock keeper shows, with the port as the answer that follows.
        scenes.forComponents(WareworksBlocks.WAREHOUSE_OUTPUT)
                .addStoryBoard("warehouse/port_requesting", PortScenes::requesting,
                        WareworksPonderTags.WAREHOUSE, AllCreatePonderTags.LOGISTICS);

        // Also a scene of the stock keeper: a maximum that makes a warehouse input back up (warehouse/stock_rules) is
        // exactly what an accepting port answers, and a player who read the one needs to find the other.
        scenes.forComponents(WareworksBlocks.WAREHOUSE_OUTPUT, WareworksBlocks.WAREHOUSE_STOCK_KEEPER)
                .addStoryBoard("warehouse/port_accepting", PortScenes::accepting,
                        WareworksPonderTags.WAREHOUSE, AllCreatePonderTags.LOGISTICS);

        // The third direction (M18, issue #13), last again for the same reason. Also a scene of the <b>production
        // station</b>: closing the loop — the crane brings the ingredients and takes the product back — is exactly what
        // that block's story needs, and a player who read warehouse/production has to find this one.
        scenes.forComponents(WareworksBlocks.WAREHOUSE_OUTPUT, WareworksBlocks.WAREHOUSE_PRODUCTION)
                .addStoryBoard("warehouse/port_collecting", PortScenes::collecting,
                        WareworksPonderTags.WAREHOUSE, AllCreatePonderTags.LOGISTICS);
    }
}
