package dev.wareworks.client.ponder;

import com.simibubi.create.infrastructure.ponder.AllCreatePonderTags;
import com.tterrag.registrate.util.entry.ItemProviderEntry;
import com.tterrag.registrate.util.entry.RegistryEntry;

import dev.wareworks.client.ponder.scenes.CraneScenes;
import dev.wareworks.client.ponder.scenes.NetworkScenes;
import dev.wareworks.client.ponder.scenes.PackageScenes;
import dev.wareworks.client.ponder.scenes.PortScenes;
import dev.wareworks.client.ponder.scenes.ProductionScenes;
import dev.wareworks.client.ponder.scenes.RackBayScenes;
import dev.wareworks.client.ponder.scenes.StockRuleScenes;
import dev.wareworks.client.ponder.scenes.TerminalScenes;
import dev.wareworks.client.ponder.scenes.WarehouseScenes;
import dev.wareworks.registry.WareworksBlocks;
import net.createmod.ponder.api.registration.PonderSceneRegistrationHelper;
import net.minecraft.resources.ResourceLocation;

/**
 * Which scene is shown for which item.
 * <p>
 * The component of a storyboard is the <b>item id</b>: it decides whose tooltip says "Hold [W] to Ponder" and what
 * {@code /ponder <id>} opens. Every Wareworks block therefore appears as a component of at least one scene, and blocks
 * that take part in several stories get several (scene order per component is registration order).
 * <p>
 * The tags passed to {@code addStoryBoard} only make those tags flash in the UI; membership is in
 * {@link WareworksPonderTags}.
 * <p>
 * Schematic paths resolve to {@code assets/wareworks/ponder/<path>.nbt} and are generated by
 * {@code scripts/gen_ponder_schematics.py}. Scene ids (the first argument of {@code scene.title}) must be unique
 * within the {@code wareworks} namespace, because they are the lang key prefix of the scene's texts.
 * <p>
 * The scene count per component is asserted by the {@code ponder} visual scenario
 * ({@code dev.wareworks.dev.PonderVisualScenario}), so a lost registration fails that run.
 *
 * <table>
 *   <caption>Scenes per component</caption>
 *   <tr><th>Component</th><th>Scenes</th></tr>
 *   <tr><td>stacker_crane, warehouse_rail</td><td>stacker_crane/overview, warehouse/corner,
 *       warehouse/junction</td></tr>
 *   <tr><td>warehouse_interface</td><td>warehouse/interface, warehouse/filters, warehouse/storing</td></tr>
 *   <tr><td>warehouse_controller</td><td>warehouse/storing, warehouse/retrieving</td></tr>
 *   <tr><td>warehouse_input</td><td>warehouse/storing, warehouse/packages_at_the_door</td></tr>
 *   <tr><td>warehouse_output</td><td>warehouse/retrieving, warehouse/port_requesting, warehouse/port_accepting,
 *       warehouse/port_collecting, warehouse/packages_at_the_door</td></tr>
 *   <tr><td>warehouse_terminal</td><td>warehouse/terminal, warehouse/requesting,
 *       warehouse/production_chain</td></tr>
 *   <tr><td>warehouse_production</td><td>warehouse/production, warehouse/port_collecting,
 *       warehouse/production_chain</td></tr>
 *   <tr><td>warehouse_stock_keeper</td><td>warehouse/stock_rules, warehouse/restocking,
 *       warehouse/port_accepting</td></tr>
 *   <tr><td>rack_bay_wood, rack_bay_andesite, rack_bay_brass</td><td>warehouse/rack_bay, warehouse/rack_wall,
 *       warehouse/bays_in_an_aisle</td></tr>
 * </table>
 */
public final class WareworksPonderScenes {
    private WareworksPonderScenes() {
    }

    public static void register(PonderSceneRegistrationHelper<ResourceLocation> helper) {
        PonderSceneRegistrationHelper<ItemProviderEntry<?, ?>> scenes = helper.withKeyFunction(RegistryEntry::getId);

        scenes.forComponents(WareworksBlocks.STACKER_CRANE, WareworksBlocks.WAREHOUSE_RAIL)
                .addStoryBoard("stacker_crane/overview", CraneScenes::overview,
                        WareworksPonderTags.WAREHOUSE, AllCreatePonderTags.KINETIC_APPLIANCES);

        scenes.forComponents(WareworksBlocks.WAREHOUSE_INTERFACE)
                .addStoryBoard("warehouse/interface", WarehouseScenes::warehouseInterface,
                        WareworksPonderTags.WAREHOUSE);

        scenes.forComponents(WareworksBlocks.WAREHOUSE_INTERFACE)
                .addStoryBoard("warehouse/filters", WarehouseScenes::storageFilters,
                        WareworksPonderTags.WAREHOUSE);

        scenes.forComponents(WareworksBlocks.WAREHOUSE_INPUT, WareworksBlocks.WAREHOUSE_CONTROLLER,
                        WareworksBlocks.WAREHOUSE_INTERFACE)
                .addStoryBoard("warehouse/storing", WarehouseScenes::storing,
                        WareworksPonderTags.WAREHOUSE, AllCreatePonderTags.LOGISTICS);

        scenes.forComponents(WareworksBlocks.WAREHOUSE_OUTPUT, WareworksBlocks.WAREHOUSE_CONTROLLER)
                .addStoryBoard("warehouse/retrieving", WarehouseScenes::retrieving,
                        WareworksPonderTags.WAREHOUSE, AllCreatePonderTags.LOGISTICS);

        scenes.forComponents(WareworksBlocks.WAREHOUSE_TERMINAL)
                .addStoryBoard("warehouse/terminal", TerminalScenes::placing,
                        WareworksPonderTags.WAREHOUSE);

        scenes.forComponents(WareworksBlocks.WAREHOUSE_TERMINAL)
                .addStoryBoard("warehouse/requesting", TerminalScenes::requesting,
                        WareworksPonderTags.WAREHOUSE, AllCreatePonderTags.LOGISTICS);

        scenes.forComponents(WareworksBlocks.WAREHOUSE_PRODUCTION)
                .addStoryBoard("warehouse/production", ProductionScenes::production,
                        WareworksPonderTags.WAREHOUSE, AllCreatePonderTags.LOGISTICS);

        scenes.forComponents(WareworksBlocks.WAREHOUSE_STOCK_KEEPER)
                .addStoryBoard("warehouse/stock_rules", StockRuleScenes::stockRules,
                        WareworksPonderTags.WAREHOUSE, AllCreatePonderTags.LOGISTICS);

        scenes.forComponents(WareworksBlocks.WAREHOUSE_STOCK_KEEPER)
                .addStoryBoard("warehouse/restocking", StockRuleScenes::restocking,
                        WareworksPonderTags.WAREHOUSE, AllCreatePonderTags.LOGISTICS);

        // The two port scenes come last on purpose (M17, issue #12): scene order per component is registration order,
        // so registering them here leaves warehouse/retrieving the first thing a warehouse output shows and
        // warehouse/stock_rules the first thing a stock keeper shows, with the port as the answer that follows.
        scenes.forComponents(WareworksBlocks.WAREHOUSE_OUTPUT)
                .addStoryBoard("warehouse/port_requesting", PortScenes::requesting,
                        WareworksPonderTags.WAREHOUSE, AllCreatePonderTags.LOGISTICS);

        // Also a scene of the stock keeper: a maximum that makes a warehouse input back up (warehouse/stock_rules) is
        // exactly what an accepting port answers, and a player who read the one needs to find the other.
        scenes.forComponents(WareworksBlocks.WAREHOUSE_OUTPUT, WareworksBlocks.WAREHOUSE_STOCK_KEEPER)
                .addStoryBoard("warehouse/port_accepting", PortScenes::accepting,
                        WareworksPonderTags.WAREHOUSE, AllCreatePonderTags.LOGISTICS);

        // The third direction (M18, issue #13), last again for the same reason. Also a scene of the <b>production
        // station</b>: closing the loop — the crane brings the ingredients and takes the product back — is exactly what
        // that block's story needs, and a player who read warehouse/production has to find this one.
        scenes.forComponents(WareworksBlocks.WAREHOUSE_OUTPUT, WareworksBlocks.WAREHOUSE_PRODUCTION)
                .addStoryBoard("warehouse/port_collecting", PortScenes::collecting,
                        WareworksPonderTags.WAREHOUSE, AllCreatePonderTags.LOGISTICS);

        // Recursive production (M20, issue #4, ADR-032), and registered last for the same reason as the port scenes: it
        // is the answer that follows warehouse/production and warehouse/requesting, not the first thing either block
        // should show. It belongs to <b>both</b> — the chain is planned by a click at a terminal and run at the
        // stations — so a player who met one half finds the other.
        scenes.forComponents(WareworksBlocks.WAREHOUSE_PRODUCTION, WareworksBlocks.WAREHOUSE_TERMINAL)
                .addStoryBoard("warehouse/production_chain", ProductionScenes::chain,
                        WareworksPonderTags.WAREHOUSE, AllCreatePonderTags.LOGISTICS);

        // Rails around a corner (M21, issue #1, ADR-033), and last for the same reason as the scenes above: a player
        // meets "what a stacker crane is" first and "and the rails may bend" after it. It belongs to <b>both</b> the
        // rail and the crane — the rails decide where the warehouse goes, the machine is what turns on them — so a
        // player who picked up either one finds it.
        scenes.forComponents(WareworksBlocks.WAREHOUSE_RAIL, WareworksBlocks.STACKER_CRANE)
                .addStoryBoard("warehouse/corner", NetworkScenes::corner,
                        WareworksPonderTags.WAREHOUSE, AllCreatePonderTags.KINETIC_APPLIANCES);

        // Rails that split (M22, issue #2, ADR-035), and after the corner for the same reason the corner comes after
        // the overview: a player meets "what a stacker crane is", then "the rails may bend", then "and they may
        // split". It belongs to the same two components, because it is the same two blocks that make it happen.
        scenes.forComponents(WareworksBlocks.WAREHOUSE_RAIL, WareworksBlocks.STACKER_CRANE)
                .addStoryBoard("warehouse/junction", NetworkScenes::junction,
                        WareworksPonderTags.WAREHOUSE, AllCreatePonderTags.KINETIC_APPLIANCES);

        // Packages at a door (M26, issue #18, ADR-040), and last for the same reason as every scene above: a player
        // meets "a port hands items out" and "an input takes items in" first, and "and a Create Packager can box them
        // on the way" after. It belongs to <b>both</b> doors — the build is the same block on either side of the
        // warehouse, and which station its back touches is the whole lesson — so a player who met one finds the other.
        scenes.forComponents(WareworksBlocks.WAREHOUSE_OUTPUT, WareworksBlocks.WAREHOUSE_INPUT)
                .addStoryBoard("warehouse/packages_at_the_door", PackageScenes::packagesAtTheDoor,
                        WareworksPonderTags.WAREHOUSE, AllCreatePonderTags.LOGISTICS);

        // The rack bay (M28, issue #20, ADR-048), and the one block of this mod whose scenes are deliberately NOT in
        // "warehouse first" order: a wooden bay needs no machine to craft and many players meet it as a better barrel
        // long before they own a crane, so the standalone block comes first, the wall it grows into second, and the
        // warehouse that adopts it last. All three tiers carry all three scenes, because the tier is the block and a
        // player holding a brass bay has to find the same three lessons as one holding a wooden one.
        scenes.forComponents(WareworksBlocks.RACK_BAY_WOOD, WareworksBlocks.RACK_BAY_ANDESITE,
                        WareworksBlocks.RACK_BAY_BRASS)
                .addStoryBoard("warehouse/rack_bay", RackBayScenes::rackBay,
                        WareworksPonderTags.WAREHOUSE, AllCreatePonderTags.LOGISTICS);

        scenes.forComponents(WareworksBlocks.RACK_BAY_WOOD, WareworksBlocks.RACK_BAY_ANDESITE,
                        WareworksBlocks.RACK_BAY_BRASS)
                .addStoryBoard("warehouse/rack_wall", RackBayScenes::rackWall,
                        WareworksPonderTags.WAREHOUSE);

        scenes.forComponents(WareworksBlocks.RACK_BAY_WOOD, WareworksBlocks.RACK_BAY_ANDESITE,
                        WareworksBlocks.RACK_BAY_BRASS)
                .addStoryBoard("warehouse/bays_in_an_aisle", RackBayScenes::baysInAnAisle,
                        WareworksPonderTags.WAREHOUSE, AllCreatePonderTags.LOGISTICS);
    }
}
